In [151]:
import plotly.express as px
import plotly as pl
import pandas as pd 
import json 
import numpy as np 
from bs4 import BeautifulSoup

In [152]:
with open("user_data_tiktok.json") as j:
    tiktok = json.load(j)

### The section below is exploration. The next markdown outlines the work for Milestone 1

In [153]:
tiktok

{'Comment': {'Comments': {'App': 1,
   'CommentsList': [{'date': '2026-03-15 15:44:38',
     'comment': 'Disneyland?',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-03-15 13:23:43',
     'comment': 'My fave is chip and dale!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-03-13 02:42:13',
     'comment': 'While I am sorry you’ve had to deal with all that, this gave me the greatest laugh',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-03-12 20:49:59',
     'comment': 'Love this but hate the idea of you doing child labor 😂',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-03-10 02:05:01',
     'comment': 'My favorite Disney characters are chip and dale bc your can’t separate the icons 🥰 @Gabe',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-02-14 18:18:37',
     'comment': 'Iconic',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-02-14 13:44:26',
     'comment': 'Their sizing is so inconsistent too.',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-02-05 04:05:17',
     'comment': 'CLAIMING',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-01-24 00:47:18',
     'comment': '$140 is more than I pay for my 10 week pottery class and all the materials',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-01-23 02:34:47',
     'comment': 'Boooo',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-01-23 01:33:59',
     'comment': 'OMG WHERE IS THIS!!!? We need to shoot there!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-01-14 13:49:44',
     'comment': 'I stopped buying from asos bc the sizing the the quality was so inconsistent. The free shipping and having a tall range made up for that a little. Sometimes I get ads from them and think “well maybe it’s better now.” Yeah sounds like I’m good.',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-01-07 03:59:33',
     'comment': 'Omg your outfit is so cute!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-01-06 13:22:47',
     'comment': 'This is a crime against humanity',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2026-01-03 21:51:24',
     'comment': 'Is she the finna be in the pit girl 😂',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-12-23 23:45:06',
     'comment': 'When I got married I told them the vegan and vegetarian meal needed to be two separate things bc I needed cheese at the wedding and I had multiple vegans I wanted to accommodate. And the chef made me a plate of both 🥰',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-11-30 01:13:31',
     'comment': 'What size frames did you buy? They look SO good',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-11-22 02:33:58',
     'comment': 'The costumes. The dance moves. The confidence. The TALENT. Nothing short of incredible',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-11-13 01:33:41',
     'comment': 'I fear I may need one',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-11-10 18:22:29',
     'comment': 'This was REALLY interesting.',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-11-07 22:42:52',
     'comment': 'Every time I fly out of Cleveland the line looks like that. I’ve waited over an hour on a random Tuesday morning. It’s inefficient and a poor set up for morning travel, I bought precheck bc of it',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-10-10 21:27:39',
     'comment': '💀 I got gazpacho and geppetto mixed up when I was looking right at him at Disneyland',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-09-28 16:44:44',
     'comment': 'They were so set on keeping who got eliminated as secret but they spoiled the finale by including the final 3 on the runway in the thumbnail on Hulu before the episode was released 😂',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-09-09 00:41:28',
     'comment': 'Dropped a class bc the professor told me “think of me as your peer” and then assigned 12 hours of reading a week with TWO homework assignments and having to teach myself figma',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-09-04 15:57:56',
     'comment': 'I reverse imaged searched and it brought up a couple options on Amazon, Walmart, SHEIN, and ASOS',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-09-04 12:51:09',
     'comment': 'This is iconic',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-09-01 21:03:41',
     'comment': 'Literally forever glad the sunglasses photos exist',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-08-29 22:22:07',
     'comment': 'SCALLION CREAM CHEESE IN OHIO!? I haven’t been able to find it since leaving NY!!!!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-08-28 11:17:52',
     'comment': 'I also stopped saying the pledge in 4th grade bc I asked what “allegiance” meant and a kid told me “it means you’re willing to die for this country.” And my teacher went “he’s right.” And I wasn’t ready to die so I did a lipsyncing situation for the rest of elementary school or would purposely be late to miss it',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-08-26 11:44:00',
     'comment': 'All of the outfits are literally PERFECT!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-08-24 19:33:09',
     'comment': 'My great uncle has fallen for it MULTIPLE times. He thinks they all can’t be lying 💀💀',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-07-15 02:06:13',
     'comment': 'In 4th grade all the books we read in class were about war. When my mom asked the school why they said “this is the age when boys usually check out of reading.” My mom was like “my daughter is actively checking out of reading!” The next year it was STILL all books about war to cater to them.',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-06-30 03:02:56',
     'comment': 'MOE',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-06-27 02:21:32',
     'comment': 'Build a little shrine!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-06-25 02:46:33',
     'comment': 'FUCK THATS BRILLIANT',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-06-19 20:17:24',
     'comment': 'I was in an AI ethics class and the kid next to me flat out told the professor “yeah I haven’t written an essay in years. It’s all chat gpt” and we literally had an essay due that week',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-06-18 18:32:09',
     'comment': 'I saw her open for childish Gambino last year and she said she was going to throw it back and play some oldies. I thought we were getting i whip my hair, nope a song from 2021',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-06-02 02:13:57',
     'comment': '@Gabe omg this would look so good on you',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-05-31 18:04:05',
     'comment': '292026852015',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-05-24 03:14:02',
     'comment': 'Seeds! They will give you seeds!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-05-20 03:30:10',
     'comment': 'The pad Thai used to be so good. But it fell from grace 😔',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-05-17 16:44:17',
     'comment': '🫡🫡🫡',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-05-16 03:21:24',
     'comment': 'You should have qualified king 😢😔',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-05-12 02:22:32',
     'comment': 'Vulpix!!!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-05-01 02:28:13',
     'comment': 'I think about how before there was Just Egg they made a chipotle vegan mayo that tasted exactly like the creamy jalapeno sauce on quesadillas at chipotle. I still dream they bring it back',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-04-24 21:44:39',
     'comment': 'I work in college dining (at another school) and let me tell you you’re doing the right thing! I’m always advocating from the inside but they do take student feedback seriously.',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-03-27 11:48:12',
     'comment': 'When I was looking for wedding photographers if they didn’t have a fat person in on their website I wouldn’t reach out to them. It was SHOCKING how many people I had to skip.',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-03-13 02:18:19',
     'comment': 'Queen come to the US 🇺🇸',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-03-13 02:10:40',
     'comment': 'Fuck that’s so chic',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-03-10 23:05:14',
     'comment': 'I got an email that was very clearly written by ChatGPT',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-03-10 19:28:34',
     'comment': 'No bc this song isn’t on Spotify in the states and I need it',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-03-03 19:56:33',
     'comment': 'Literally got precheck bc everytime I fly for work they book me on an early morning flight and I used to wait 1-2 hours just to get through security.',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-03-01 04:58:34',
     'comment': '@Meredith Marks core',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-02-04 01:21:10',
     'comment': 'Let me download this so I can put in the family gc',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-02-01 19:13:39',
     'comment': 'TAKE MY MONEY',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-01-25 13:43:58',
     'comment': 'Bestie restock the XL!! I found out too late 😭😭',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-01-14 03:01:35',
     'comment': 'AND FETA SHOULD NOT BE MADE WITH COWS MILK 👏🏻👏🏻👏🏻',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2025-01-13 22:45:08',
     'comment': 'You know what? Hell yeah',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-12-31 02:30:32',
     'comment': 'No bc I wanted one skirt ended up buying it in three colors and then bought two tops 🙈',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-12-27 00:09:32',
     'comment': 'Does it drop at midnight on the 28th? I gotta get that skirt before it sells out',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-12-15 17:00:45',
     'comment': 'Go birds 🦅',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-12-15 14:52:05',
     'comment': 'Omg where did you get your Mr toad ears!?',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-12-15 02:34:23',
     'comment': 'I wore a hannukkah pjs to a pj holiday party and someone asked if I was being ironic 💀',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-12-07 04:38:42',
     'comment': 'M when I got mine I looked at the wall next to me and it was a framed stock photo of this guy who bullyed me in high school 💀',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-11-29 03:04:52',
     'comment': 'I once posted an Instagram post here calling it one of the nations most important monuments and a random commented “these sculptures don’t have a historical story.”',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-11-27 21:52:23',
     'comment': 'Not only do I get it, I feel it in every bone in my body',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-11-10 20:58:37',
     'comment': 'Here for carrot 🫡 lost my cat beefcake to cancer and we found out too late so I am ROOTING for you carrot (get it? 🥕)',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-10-28 19:34:11',
     'comment': 'I fully said “I FUCKING KNEW IT” 🤦🏻\u200d♀️',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-10-19 23:09:46',
     'comment': 'Bestie if you are where I think you are i desperately need to know if you had the strange buzz aldrin chair in the room just staring at you making these',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-10-10 14:03:11',
     'comment': 'HAPPY BIRTHDAY',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-09-25 22:13:22',
     'comment': 'Go birds 🦅',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-09-24 18:59:29',
     'comment': 'Whoever thought of fall oat boy is a creative genius and my only criticism is y’all are not close to me so I can have one',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-09-23 18:48:47',
     'comment': 'Omg going on the Fantasy in January! Need food and drink recs!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-09-18 03:03:21',
     'comment': 'I am a size 8.5 looking for that sole mate 👟',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-09-18 02:10:44',
     'comment': 'Too real 💀',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-09-12 01:17:20',
     'comment': 'I had a coworker come to work the week of my wedding saying she had allergies. It was pink eye.',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-08-31 00:59:24',
     'comment': 'On my wedding morning none of us could poop, we were really all in it together eating oatmeal and downing coffee. It worked for everyone 🫡 we bonded even more bc of it',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-08-16 11:17:57',
     'comment': 'Ithaca is also insanely expensive. I think it’s the second most expensive college town, behind Boston.',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-08-13 02:14:01',
     'comment': 'They’re SO CUTE 💕',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-08-04 02:25:23',
     'comment': 'No bc someone at work told me this and I was like “what?” And I googled it in front of her and she was like “I swear I saw it on the news” BRUH',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-07-15 23:28:01',
     'comment': 'I loved when they were like btw custom shirts are on sale and we think you should buy one to support trump',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-07-15 22:45:13',
     'comment': 'I use stickerapp which I love bc I put QR codes on the back!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-06-04 01:00:02',
     'comment': 'I need the full song immediately ❤️',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-06-02 11:49:25',
     'comment': 'No bc the beads that match your eyes are perfect',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-05-19 12:29:31',
     'comment': 'Once I bought an eggplant and the cashier was like “nice, like the emoji” then small talk then asked me what it was actually called. Hilarious and I hope he’s thriving now knowing what an eggplant is.',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-04-21 22:43:42',
     'comment': 'Commenting to boost in the Al gore rhythm ❤️hopefully y’all are reunited soon 💕',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-03-26 05:34:58',
     'comment': 'I can’t believe the for you page showed this to me after my wedding.',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-03-19 09:25:55',
     'comment': 'This is the sweetest most unexpected comment. Unfortunately we lost beefcake to cancer at the end of last year. His loss was unexpected and sudden but he was happy until the very end and loved still!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-03-06 03:28:08',
     'comment': 'We need to Pokémon go to the polls',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-03-06 02:09:39',
     'comment': 'Not the ad immediately following this',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-02-17 03:26:54',
     'comment': 'Me to my boss at our weekly one on one',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-02-15 23:28:15',
     'comment': 'I had a florist tell me they couldn’t tell me their shop minimum until we had a 90 minute consultation. WTF',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-02-15 03:33:18',
     'comment': 'Damn this is really the for YOU page 💀',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-01-29 11:45:48',
     'comment': 'Came here to comment the same thing. I bought something online and then got ghosted by the company, filled a free complaint and got my money back within 2 weeks and a call from the owner apologizing.',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-01-28 13:16:39',
     'comment': 'My supermarket made a bunch of browns stuff week one of the playoffs. Got a dozen cupcakes for about $4 after they didn’t advance 😂',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-01-17 02:21:12',
     'comment': '🫡🫡🫡 go birds 🦅',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2024-01-14 22:49:08',
     'comment': 'A stab in my vegetarian heart 😭',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2023-12-31 15:23:23',
     'comment': 'Where you cropped that dress to us literally the perfect length. the vision and execution are PERFECTION!!!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2023-12-29 03:50:15',
     'comment': 'Sam’s has top tier churros. I love Costco for everything else but their churro was a miss. Didn’t like the half and half dough',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2023-12-28 17:05:07',
     'comment': 'Honestly the program directors are probably the same folks and really lean into being a “heritage” station (Aka “if it ain’t broke don’t fix it”)',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2023-12-27 17:43:48',
     'comment': 'A honeymoon counts as a family trip right 👀👀👀',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2023-12-27 17:41:12',
     'comment': 'Listen I’m not saying to drop your friend code in the comments but if you added me I would send your poke gifts from my library!',
     'photo': 'N/A',
     'video': 'N/A',
     'url': ''},
    {'date': '2023-12-27 15:03:21',

In [154]:
type(tiktok)

dict

In [155]:
tiktok.keys()

dict_keys(['Comment', 'Direct Message', 'Income+ Wallet', 'Likes and Favorites', 'Location Review', 'Post', 'Profile And Settings', 'TikTok Live', 'TikTok Shop', 'Your Activity'])

In [156]:
tiktok["Your Activity"]

{'Ad Interests': {'AdInterestCategories': ','},
 'Ads Visit History': {'AdsVisitHistoryList': [{'CreateTime': '2025-11-08 15:32:14',
    'AdTitle': 'Christmas : Target',
    'AdLink': 'https://www.target.com/c/christmas/-/N-5xt30?TCID=SMP-1847411527626769-1847412809923602-1847962512477265&ttclid=E_C_P_CtwBFdvlGnauO1CQVvQ11QCOfZ4OS4gj08NnDxw73Q7bqyrtURS8eYChII8bZU0Kb6tiYuXPFZhv96pOSIl661vsqqBMjGoRDO3FFqicxp4IdJVqucLF6R-T1DU0wnBhpy-qViXXO9anATKYd_Qoc0tTx47Ou01_WWe_n5zoKrR9BWX025XVYfXExtbn-fZxbIx6QsjNBWYTC8GIoWl9JKAGYomAus_Wbm5nA2R8nekJJ9cgISqn1OktsRy4xsXBDPNTG2p-qZcBR4t1i0yhTVTJCQTMncDPIcNUeIAvXxIEdjIuMA'},
   {'CreateTime': '2025-11-11 02:02:01',
    'AdTitle': "A.1. Sauce: It's Not Meatloaf, It's Beefcake Campaign | United States | Kraft Heinz",
    'AdLink': 'https://www.kraftheinz.com/a1beefcakes?utm_medium=paidsocial&utm_source=tiktok&utm_campaign=1847801379103778&utm_adgroup=1847800631884978&utm_content=1847954492354609&ttclid=E_C_P_Ct0BzBm9idU_zLgMR6zpuJPjrp4YmEK0mhN-wvf8uN0Q6kBfxYKAbdah12dgC84blULiBd832GMVmfVYy5MwJ-pFJ8OZZmalx6E5UtjTGMFl5VR0yCCR-5w5y9ItbxBK51cYyomvdq2_H7zxgjUCbxQR6-d7AV35EhlXcJsqESRy0H0adpp0ju84h6_aS5BDXqKErlEdfsLfp4cA3KN9jIFQ0w9vFkTr5ZDHllX4bkdXzSE-KEeU2tAEC6LKpgxoYoKSeSwbf7UIAV7d5NB7uZYBAdE-pfEkk06Q1ix0MIQSBHYyLjA'},
   {'CreateTime': '2025-11-11 03:22:24',
    'AdTitle': 'New Ray-Ban Meta AI Glasses - Shop Gen 2 & Gen 1 | Meta Store',
    'AdLink': 'https://www.meta.com/ai-glasses/ray-ban-meta/?utm_source=tt&utm_medium=paidsoc&utm_campaign=1845345555199089&utm_parent=rbm&utm_ad=1848159168481297&utm_placement=TikTok&utm_funnel=dgen&ttclid=E_C_P_Ct0B9Apu6sBT5cFFW0fpBRxbul1ND25R_jOkPOlpZL4y7ykJKo0tzEFw5onm8Oir9EFiPxAHzG1FMUXyGqQJOTNMmILIRSgI5Pqe1GQyA24NOOPdYQYurelpXJBvbKFt3yIOMCyUHnEP7xe2BEOrFM8K1lWieI1ZFgQ0gx1oq2MjmtIKldRVxqc7rfjUlgD_PjiBZKghcNAFcaabzRwgrK_hPCxcl9MZBSZsWA119MYh_H8Ky24dmcmpHPjBPct8oufyXuyGh1HkF9kunF8hCXpDkZ87YyLVVYaB79JTu8MSBHYyLjA'},
   {'CreateTime': '2025-11-19 12:33:17',
    'AdTitle': 'Shaping Dresses That Sculpt & Support | TA3',
    'AdLink': 'https://ta3swim.com/collections/shaping-dresses?nb_platform=tiktok&nbt=nb%3Atiktok%3A%3A1837310466264081%3A1837310540068914%3A1848811570889857&tt_campaignid=1837310466264081&utm_campaign=US%20%7C%20Pros%20%7C%20SmartSpark%20%7C%20DressLP&utm_id=1837310466264081&utm_medium=paid&utm_source=tiktok&ttclid=E_C_P_CuEBHll1iSr8A4FvfXoDm10AitQjnPL73DSTpMuIY8zMaZoqo2gFKIgI-1NT6X49XYo9W3xzhJGZNBhm6ne_9ZFtkpKyWi2CruMgeB9tSD7uFYWDSkBhdbkIl_M0C6ibqaO14UCCgGX3SC0lWEgkAkISAd7uIbTuyLbnRaeDZ5v8DUwTH4I4gQcfiZ4eZPsqTOOPu67oqtGFM7LkX1OogVs8MALMISbp8hvfTqAECXMoFKpyO_iyOejrcXzJPSDntEUIaiWMNjed7-a0ci6QWoZERAMLSCdXoUOScvXB_esFYmKoEgR2Mi4w'},
   {'CreateTime': '2025-11-20 03:23:10',
    'AdTitle': 'Insurance Quote | Liberty Mutual',
    'AdLink': 'https://www.libertymutual.com/multi-online-quotes?selectedOpt=auto_home&cid=soc&cmpgncde=2405&keyCode=SMFCTC00&src=cm-dsoc-aut-TikTok-Brand&utm_source=tiktok&utm_medium=paid&utm_id=1847233309232306&utm_campaign=November%2FDecember%202025%20Reach&ttclid=E_C_P_Ct4BOv9zgRfi227kvYx3_d7YzrCt6XTN0mQrpRBezFnyibZamC39eH0zglps4M0XwPaWnWQcvTkBhBHe0koMLWADgpIbl5BKnPMYbnIOePjlY37bEzQfpD-0zHGang9afent89B8F70xBdrr6e-Mlvk9Zad0BD888kfwzFNlW7V78uJaQUNjUKLR9lZEebUNmAhOrFsW9e6CUmmGgiKLBiuA9nG77EbzhnTTnBfkK5b1N7o6zJ2XRc2Ap1Ymt1fG_wDwIsaasbyRi9wp7CEMXhBvlzh3W05hkcYBNs3cpTxqEgR2Mi4w'},
   {'CreateTime': '2025-11-20 20:20:17',
    'AdTitle': 'Taco Bell New Menu Items: Order Online for Pickup or Delivery | Taco Bell®',
    'AdLink': 'https://www.tacobell.com/food/new?utm_source=tiktok&utm_medium=paid-social&utm_campaign=crispychicken&utm_term=launch&ttclid=E_C_P_CtwBurPf6_J3QgPVs6Px56Gl7xIFe8pQZ_6mTRyaxEmDL1WtO7cmYh_Sv4io0lucdyPPNwr91Z5m0QkO0QhjzSesxSN2kJcsUEUt9jb-dlgXpUty0dNkM88wopfcWcgHqYmm93A2Hr_v2Z8IoSPctSLl9bByOjfQPMCbNN85EjVa0olOyRlVcuJ2-0V5KcTRnMijY3aCEP4OZnjMylAH13KfbU62FhEV6WTfLYX9gIlB1r8bB_NmbjD1IyCYy_j2X4iMO6eE2eeo0XFvK0eT9XmbbgVkCjNTYBh8e7_KYxIEdjIuMA'},
   {'CreateTime': '2025-11-24 02:27:30',
    'AdTitle': 'Home Decor Store and More | HomeGoods',
    'AdLink': 'https://www.homegoods.com/?ttclid=E_C_P_Ct4BIAPUDNsuBn9B7z7eoS5qsMkOABIMvo6hTFb8X21EqjCOr49tzGi5GKTKH4EoaFd9FZrAm-kYzui2tWlYhm_aC35RVDhm6FoKz8zz5yG7rTsUWP0EHuI5oTaEgTLQemznR9f-HBfuEosd-raXEI8qCYxNrBHu916nAj71vUzfkg7tJ5VQ0BNabYABNx0XBhbV15uJrf3hBTZ2Pvlj2qobZ13xmYKw9hepaD7klYCBy2-tVKsvPYm5fkj_-qTa4EPRVa-amg_IdvQV_0-7Z9Dm9kK0JByeiFav8-wHh-OBEgR2Mi4w'},
   {'CreateTime': '2025-11-24 02:27:30',
    'AdTitle': 'N/A',
    'AdLink': 'https://Homegoods.com?ttclid=E_C_P_Ct4BIAPUDNsuBn9B7z7eoS5qsMkOABIMvo6hTFb8X21EqjCOr49tzGi5GKTKH4EoaFd9FZrAm-kYzui2tWlYhm_aC35RVDhm6FoKz8zz5yG7rTsUWP0EHuI5oTaEgTLQemznR9f-HBfuEosd-raXEI8qCYxNrBHu916nAj71vUzfkg7tJ5VQ0BNabYABNx0XBhbV15uJrf3hBTZ2Pvlj2qobZ13xmYKw9hepaD7klYCBy2-tVKsvPYm5fkj_-qTa4EPRVa-amg_IdvQV_0-7Z9Dm9kK0JByeiFav8-wHh-OBEgR2Mi4w'},
   {'CreateTime': '2025-11-26 02:15:07',
    'AdTitle': 'Eternity (2025) Movie Tickets & Showtimes Near You | Fandango',
    'AdLink': 'https://www.fandango.com/eternity-2025-241449/movie-overview?date=2025-11-25&utm_source=tiktok&utm_medium=paid&utm_id=1849089491465233&utm_campaign=Eternity%20%7C%20Pre-Release%20%7C%20T-0%20%7C%20BookTok%2C%20Romance%20Film%20%26%20TV%2C%20KM%2C%20KM%20LAL%2C%20RTG%20%28Eternity%2BMats%29%20%7C%20Earned%20Media%20%26%20Statics%20%7C%20Conversion%20%7C%20IC%20%7C%20TG%20%231%20%7C%20TikTok%20%7C%20Auction&ttclid=E_C_P_CuABW64FvbvYoaku2-Y5EyZHdrUvlmwmBDiGJYn09rjg3PNo1VD4-thNhxfTwJizeOxfLSMyYMi61CK5L_5-XxIp1egZR7s-vHc4z3zZ2EI5S9unmJ2JEuT7GfstmlvRdYNUiQ30Sk6RoAVsUeHRUpurMPeLwA0fdh3N870Eb5rqMW_16aq-YbR3J_gCIuUDMX68HZgaL78yHRprNViv5PovfIB5kMJ7N5-T6pv2jmwwDQvIlXqKdaNgik2QAd-mz6kPhejckX_c5lsLDX1FTguEBvaWkeA1GVkwu9yN7gh_b4wSBHYyLjA'},
   {'CreateTime': '2025-11-26 02:15:26',
    'AdTitle': 'Eternity (2025) Movie Tickets & Showtimes Near You | Fandango',
    'AdLink': 'https://www.fandango.com/eternity-2025-241449/movie-overview?date=2025-11-25&utm_source=tiktok&utm_medium=paid&utm_id=1849089491465233&utm_campaign=Eternity%20%7C%20Pre-Release%20%7C%20T-0%20%7C%20BookTok%2C%20Romance%20Film%20%26%20TV%2C%20KM%2C%20KM%20LAL%2C%20RTG%20%28Eternity%2BMats%29%20%7C%20Earned%20Media%20%26%20Statics%20%7C%20Conversion%20%7C%20IC%20%7C%20TG%20%231%20%7C%20TikTok%20%7C%20Auction&ttclid=E_C_P_CuABW64FvbvYoaku2-Y5EyZHdrUvlmwmBDiGJYn09rjg3PNo1VD4-thNhxfTwJizeOxfLSMyYMi61CK5L_5-XxIp1egZR7s-vHc4z3zZ2EI5S9unmJ2JEuT7GfstmlvRdYNUiQ30Sk6RoAVsUeHRUpurMPeLwA0fdh3N870Eb5rqMW_16aq-YbR3J_gCIuUDMX68HZgaL78yHRprNViv5PovfIB5kMJ7N5-T6pv2jmwwDQvIlXqKdaNgik2QAd-mz6kPhejckX_c5lsLDX1FTguEBvaWkeA1GVkwu9yN7gh_b4wSBHYyLjA'},
   {'CreateTime': '2025-11-28 13:58:55',
    'AdTitle': 'Black Friday Deals 2025 | Amazon.com',
    'AdLink': 'https://www.amazon.com/blackfriday?ttclid=E_C_P_CtwBG_iXHuFbkuNCmGxCaSyi2Lbsu7Q3_9GF9dduq0ND9Ji60l0jq3N7bbs8LxqCfmJOi9MiXjIP694wtOJIj-Hf0NBGwPJ3Vylv1sU7ci-Cyv7BGs3jRIsqyFc9425BdzvtoJxzUQPDOv9uWVKbnZb0YGS1i5pP0amcPnO_YJ9V3C-6NB3F0Rf-mYQ5OAqHfEdGxOZR6_zojnDtZKDUEe8fsJGVkwn_D0mHFE8-Y_iDwHtSDDfoHOD4pVfvL1sMKfixq8uFme_zGzIOVsQGQc01Mc2YZlKWOuInj_tDhhIEdjIuMA'},
   {'CreateTime': '2025-11-28 16:28:16',
    'AdTitle': 'Bras and Panty Sets - Shop Sexy Matching Underwear Sets | Adore Me',
    'AdLink': 'https://www.adoreme.com/bras-and-panties?utm_source=Paid&utm_medium=TikTok&utm_id=1836636179355682&utm_campaign=Prospecting%20-%20Broad%20Women%20-%20Smart%2B%20-%20VSA%20-%20V2&ttclid=E_C_P_CuEB0MyH9eqwM_5_Ae7s6pjcSoQ8ic20L7dGM0XZfz5O6AMyV0gNedSjLlgZFxNnIJuhshY8HdX4e60725rZqXHywI5iqgQdIrMAFLIQ0v0NMGH_65B-GoZacRCu6M_bcjqn3TRMPFRn_puKQQrLCHwjFVayfdWXtsfd1UQA9lYQYKAnJg5Dn2y0NH332A6Pr4HvCIpBBO4KTr1oGst6VUOy1i31OcJ9kl7xzooO3k2AZlre72bEI7F9bLsnOtr8ikGc0Z1H8PkV41ij3tjTalWNZV5euuTLeA2IQhlI2KF1eccbEgR2Mi4w'},
   {'CreateTime': '2025-11-28 22:16:15',
    'AdTitle': 'Dresses - JessaKae',
    'AdLink': 'https://jessakae.com/collections/dresses?filter.v.availability=1&sort_by=manual'},
   {'CreateTime': '2025-11-28 22:16:14',
    'AdTitle': 'N/A',
    'AdLink': 'https://jessakae.com/collections/dresses?filter.v.availability=1%3Ftw_adid%3D1824415958319170&tt_campaignid=1824415927154929&tw_adid=1824415958319170&tw_source=tiktok&tw_source=tiktok&utm_campaign=JK+%7C+Web+Conversions+%7C+Smart%2B+Campaign&utm_id=1824415927154929&ttclid=E_C_P_CuEBLVEvvVJrC2W-UJvGp9-O8SRhi2MbBBo7yuk0YGEuS27vJQpuhk1Tj23V-fBdZrM0wO2gsFOfl-YmuEM1sXf4oi6U-tqfxkXQxEaJY29TxPWmgims1YX0-E5LG_EVDLiSEtje9BrI3hEyGg8LwGhL41mvoPodD0WpgxNZfIeuu53yQZWsOBmsBqIANKm3_EEidJVaT0Q1oPNIbK_IAHdofMZOJClAcZFacsME65e-HCLZ6MMO1mWo056Ec_01mZVFs5Vlx3aPLwsa2dJNtXHT3641b44iWLlt2e59iyhEQJfOEgR2Mi4w'},
   {'CreateTime': '2025-11-28 22:16:10',
    'AdTitle': 'Dresses - JessaKae',
    'AdLink': 'https://jessakae.com/collections/dresses?filter.v.availability=1%3Ftw_adid%3D1824415958319170&tt_campaignid=1824415927154929&tw_adid=1824415958319170&tw_source=tiktok&tw_source=tiktok&utm_campaign=JK%20%7C%20Web%20Conversions%20%7C%20Smart%2B%20Campaign&utm_id=1824415927154929&utm_medium=paid&utm_source=tiktok&ttclid=E_C_P_CuEBLVEvvVJrC2W-UJvGp9-O8SRhi2MbBBo7yuk0YGEuS27vJQpuhk1Tj23V-fBdZrM0wO2gsFOfl-YmuEM1sXf4oi6U-tqfxkXQxEaJY29TxPWmgims1YX0-E5LG_EVDLiSEtje9BrI3hEyGg8LwGhL41mvoPodD0WpgxNZfIeuu53yQZWsOBmsBqIANKm3_EEidJVaT0Q1oPNIbK_IAHdofMZOJClAcZFacsME65e-HCLZ6MMO1mWo056Ec_01mZVFs5Vlx3aPLwsa2dJNtXHT3641b44iWLlt2e59iyhEQJfOEgR2Mi4w'},
   {'CreateTime': '2025-11-29 02:29:11',
    'AdTitle': 'N/A',
    'AdLink': 'https://dl.hulu.com/shows/7840bf30-f440-48d4-bf81-55d8cb24457a?%3Fcmp=21104&utm_campaign=CM_SOC_TikTok_KS7&utm_medium=Social&utm_source=TikTok&ttclid=E_C_P_Ct0B6OP8Hp1-dmggzAhRR9n1pu2RSsxG3bDgxRYCkfiL8SxKwyjS-E0b0fwx1JjB4LslLFU-WxagfK50k24T1RVXZEE9AMKG-IOIs2-d8X5S-55I0hZXGy3zqYpt46kKhipj-4zcL9gK9nLD1a2o5kPh3rDeXqZSBGN8zW3GEaz1Rr7lQjqAzSK0RhkAd6OpVylLy2mW08Udt4iCogMSK_hTYA5l89QFHayj1DAAke6rqT8UzGuyEWFR1NudOE7rkw8Xptdyyi92WNPwjdzpKM8zpdNg3EtGnBko4kfqoHQSBHYyLjA&source=web_universal_deep_linking&play=false'},
   {'CreateTime': '2025-11-29 02:29:10',
    'AdTitle': 'Watch The Kardashians Streaming Online | Hulu',
    'AdLink': 'https://www.hulu.com/series/-7840bf30-f440-48d4-bf81-55d8cb24457a?%3Fcmp=21104&utm_campaign=CM_SOC_TikTok_KS7&utm_medium=Social&utm_source=TikTok&ttclid=E_C_P_Ct0B6OP8Hp1-dmggzAhRR9n1pu2RSsxG3bDgxRYCkfiL8SxKwyjS-E0b0fwx1JjB4LslLFU-WxagfK50k24T1RVXZEE9AMKG-IOIs2-d8X5S-55I0hZXGy3zqYpt46kKhipj-4zcL9gK9nLD1a2o5kPh3rDeXqZSBGN8zW3GEaz1Rr7lQjqAzSK0RhkAd6OpVylLy2mW08Udt4iCogMSK_hTYA5l89QFHayj1DAAke6rqT8UzGuyEWFR1NudOE7rkw8Xptdyyi92WNPwjdzpKM8zpdNg3EtGnBko4kfqoHQSBHYyLjA'},
   {'CreateTime': '2025-11-29 19:19:46',
    'AdTitle': 'Disney+ | Stream Movies, TV Shows, Documentaries & More | U.S. Site',
    'AdLink': 'https://www.disneyplus.com?CID=DSS-Social-TikTok-1849164372440161-1849164950791233-1849687657492481&ttclid=E_C_P_CtwBlAO3H-xwQRkEfjn_GyFV6fRF0qA3xA1Q5b6Js3RlEOUvA89J1WOnNsKqarF-P818XTaKVa_QNrvkNeZBxUqf8JFb7M34dELmVbAPKNZLOoW98P_u8nSeQLDznKC-qIDhDKmnXMx6ZG3Dy8KkgL8fxRegrY2wy_9q2tf6hYJ7EIxOoc2hvYLDK8x76ctwl7ljlyFRrFQhiZV4uMdlJjMza0qjhdtgkhWw2C0m00-Neq9GCljIwa85o2PeGKdnYmOVVAt2fcyEweEJLuCHMao4BfpgvEZuHS7leEueXBIEdjIuMA'},
   {'CreateTime': '2025-11-29 19:19:55',
    'AdTitle': 'Ads Page – Fresh Patch',
    'AdLink': 'https://www.freshpatch.com/pages/ads?tt_campaignid=1835365688076434&utm_campaign=TikTok-Test-PROS-Smart%2B-Whitelisting%20v7&utm_id=1835365688076434&utm_medium=paid&utm_source=tiktok&ttclid=E_C_P_CuEBeHBUEEQtZfjh2tBoEyFamd8vM5ZxJ7MSHobb4tZE4K_Vq9sse9_J-HzjV_ZH5kITZ3dF7TnlNkmm-BbdFfnkh_8cf4JceilBcyq2K8aNFVpJdSE6CCB68ZsQ-_Fdl1biBpHmvufQ1mvgr5j_G1ADaxrvevcItXnBoQQaZpe7MdmaX993RDCKy7JuqfYX_vF3V6i4r00AOk9thMAY6jQPeVHE1Nz1vF_MEahQTeUhaNsYGr9lKSFkkAWz_lykD-yklprrzUkCOSo-_cRBH0NeTpEmPFX2-ZjB2bMmGumNaESjEgR2Mi4w'},
   {'CreateTime': '2025-11-30 04:17:59',
    'AdTitle': 'Disney+ | Stream Movies, TV Shows, Documentaries & More | U.S. Site',
    'AdLink': 'https://www.disneyplus.com/?CID=DSS-Social-TikTok-%7B%7Bcampaign.id%7D%7D-%7B%7Badset.id%7D%7D-%7B%7Bad.id%7D%7D&ttclid=E_C_P_CuABfnktLw8PSn0E0wp5loY9d0x-EofCpBohaeVCCpH7FRz9PCWLZTfeIgwEy65P5ywul3hc6sRxhKI3jMr0Z_axP9Uebbj8GLIiYTO1600P17gNGnd1AFBBK5Ic4c9hDQL4zfOhmCXYkQb8YqBvaBynz_aRt_ruwqvG_wfrk615buZRJAXue3NqEHLh50EaHJVCIYOHfQnn4MPYb0myhWDPlrpr2yKWV4wjcwmYUTbgPDA_KsaIge4nOiqHoz0P0CwK4t018o168M5YfVyiRpX5lxwK6WXGXpez67F5g4sV1WoSBHYyLjA'},
   {'CreateTime': '2025-12-02 20:11:35',
    'AdTitle': 'N/A',
    'AdLink': 'https://www.kerrygoldusa.com?utm_source=tiktok&utm_medium=paid&utm_id=1841636235963442&utm_campaign=Kerrygold_Sept-Dec_KRYG_KRGTM_X_NAT_F25_Q4_AO_TKT_ACQ_NTV_05925509_05931603&ttclid=E_C_P_Ct4BeNDrXOHqJJIJVhN4HVh8tM1ug1fxdqs4CiIS5-ss-r0jeaR_prst6VdQQ-FKs0XhdXaOnI9Q4pXNWBNdqOX1NyBmO17wLv3c3o-AyxpL6Uk68BqBaLOZl9xT1QhMDchu-I5yTEczzYVGTFHFOetLyDCCAndTBwv8G10oDLFuA6wOoQTPPvmGb569jCOYCleYWuHYf6ZLzenaekmimn3sN4ODE4PKB5F4Y-pxNGNttjLUokvUnt24SbQS5DL43z9SYlrvUqDF7jsP6m4mPf9pq90Ks_7kFuMs_jYbJzKxEgR2Mi4w'},
   {'CreateTime': '2025-12-04 23:35:19',
    'AdTitle': 'Amazon.com: Hasbro Games: New & Trending',
    'AdLink': 'https://www.amazon.com/stores/page/9E3D1039-B9D4-4D86-9394-46C653E44524?channel=GamesSeason25&ttclid=E_C_P_CtwBQhOPB5S-WbcBEN5_0BBGCK0hBpNlwDcth-5yv-GHX5TzDdK2royzfuy6-JrsEa01CO6D435W_-eFmDX-rZ6aF2rAVU3ToW2aEePyKWRNQl6G3Se507wh0JlEmI3G-QS8JZo59qkppc_DLL9QlFjGle4zTxPt-yt0Q37veVBmYegW96lNGvZRaoKrCxP8KYm7MS8UjvQ6SKgSFsmrrLPO6zSxhLRcayxoHpzwprFhR-PFqSTHC0WRBXpBMqoFsZH6gRt0L887o44XYJpN2rFK433uezSsQkDCGABX3RIEdjIuMA'},
   {'CreateTime': '2025-12-08 14:42:50',
    'AdTitle': "L'Oréal - Medium Lumi Glotion Natural Glow Enhancer XL, Face & Body | Ulta Beauty",
    'AdLink': 'https://www.ulta.com/p/lumi-glotion-natural-glow-enhancer-xl-face-body-pimprod2055367?sku=2642934&utm_source=tiktok&utm_medium=paid&utm_id=1844162224415089&utm_campaign=oap_makf_lum_total-lumi-phase-2-vv_auc_aw-video-views_x_x_ym00426589_q4_2025_lum_001_cbo&ttclid=E_C_P_Ct0BKL6tAq0Zpnj6U0lZhys4rUVqgDbMGvbeW0W-19dMTlAwCmHqH_wrI1m04SSOLPnpULgYMbglMff_dk6dQ_-LeOtUQIzEegnkWllGitol9wO-4shpDW5W6qqGg-4HyA9J-6uP88RQ7orEPP7USipApJ4sMqPaANNkaFyQly0M6YGS1Azpzon883NyiaZWWSSxbdNuZRwuuDEmKV16TzTvmtI0AS4Ey3VRnZB_5QvF5s9gtztEYChMI7_nenNQQuWFcVpWWym6Jw5DrqifEahPKw2m0olr7A4TAQzO1JkSBHYyLjA'},
   {'CreateTime': '2025-12-14 23:04:52',
    'AdTitle': 'New Arrivals - Outdoor Clothing | Columbia Sportswear',
    'AdLink': 'https://www.columbia.com/c/new-arrivals/?mid=brand_social&eid=tiktok&nid=Columbia_FY25_USA_Brand_Fall_TikTok_Awareness_EFW_EFW_COMBINED_AllProducts_P368CCTF_Cell1&oid=Columbia_Social_FY25_FALL_USA_English_Brand_EFW_TikTok_COMBINED_AllProducts_Awareness_Reach_Multi_Both_Interest_DynamicActives_Social_NA_NA_CrossScreen_dCPM_Skippable_Multi_NA_DynamicActivesProfessionalElites&did=FY25_USA_GlacierProducts_Lifestyle_COMBINED_Male_English_Video_30s_DITL&uid=&gid=5&ttclid=E_C_P_Ct4BiHMJmQRgKBZUI1X2MwA7f_72MWBPLxnXUimlbbO4JVGG0imY63sGT5aC_OsLzZmcT6yCvQMiEmH8GNpwL4M_eObgc3Fz01gC3q0f_rv9vlbEo4cXYJnUqs3Y8v1ne-3Q1gokhVsuxIsT8PtsflPwN0IJ-JxnEh8x2-QqhS9a-MoZTtWRWJU-clyOD_t5b_H4TQsK_mxm5cTMeHHiA43NkkUTMGa5LKRYcT1L9lh5XhF0ofakQbTQJsFjpS65skr82g-VY0jyMsNmLkQDDP2qqsPSF5H_Fptz17kp-KsEEgR2Mi4w'},
   {'CreateTime': '2025-12-20 03:33:45',
    'AdTitle': 'Shop JusRol Near You',
    'AdLink': 'https://lets.shop/2851/puffpastry_2025_tiktok/?utm_source=tiktok&utm_medium=cpc&utm_campaign=jusrol2025&utm_id=1846707943843906&ttclid=E_C_P_Ct4BuAor7V56TGNQQS7et3lDQgVUNWJYg0igHd743xXPH8EbUBeZdGL0YrCD2gMPzLpiz_XtNN8iWw4x5hmPlEnOikbdgPQsdt9TlFLr9IB9hRs0prmMtVfECknVj7WU_zHpArVeYPw_As_qY8xnemu-tPu_BZt-JlTeWJtFGkWGr1a1SMSvPeQW-Pi3BwdqqmxSji0AKquPEA8toGIGF3i8cJprw2z6N2I3pDx5Qz8dVdD0glvOLspm_nh6ux8bGgTuM-3uJVR7LOe0t-plm0nvPYS-NAbNyMm-9KleuIezEgR2Mi4w'},
   {'CreateTime': '2025-12-22 04:29:14',
    'AdTitle': 'Pumpkin Pie Spice French Toast Recipe | McCormick',
    'AdLink': 'https://www.mccormick.com/blogs/recipes/pumpkin-pie-spice-french-toast?utm_source=tiktok&utm_medium=paid-social&utm_campaign=1849328605293858&utm_term=1849328605293874&utm_content=1849328605294642&utm_id=1849328605293858&ttclid=E_C_P_Ct4BAHA5xNyh9egojeqim2Nce6_7XXJ3bXECWjmmekLvMk4Sl5dCADmpCO1HmoEzROs99QP8PdwdpZ1wq3jpP2-aXaSU2LQ7iEHvKrmKmZr2ocTxPS4-9ppyvC4hQNcsXVOCQjlyyT68QDYElkZCCFxuVYi_AqYLABsdvOWgOmmjfRYpa9f-hxBoKU1R4okxPpcb_G4y66tX3vh6P7Qp993tiWtxlTbmSzeO4IGW2rex2CEcY0NpqyDIKRTZ3K-S2TrPlEcdHh_BheH8ithKYrkxNAaCzliC0wN064ayhN7nEgR2Mi4w'},
   {'CreateTime': '2025-12-23 02:36:49',
    'AdTitle': 'Perfume & Perfumes for Women | Sephora',
    'AdLink': 'https://www.sephora.com/shop/perfume?om_mmc=coop-34683247-436098192-246436096'},
   {'CreateTime': '2025-12-23 02:36:47',
    'AdTitle': 'Perfume & Perfumes for Women | Sephora',
    'AdLink': 'https://www.sephora.com/shop/perfume?om_mmc=coop-34683247-436098192-246436096&dclid=CMyZs9LW0pEDFUYHigMdRCM4CA&gad_source=7&gad_campaignid=23342520651'},
   {'CreateTime': '2025-12-23 02:36:47',
    'AdTitle': 'N/A',
    'AdLink': 'https://ad.doubleclick.net/ddm/trackclk/N410001.3337907TIKTOK2/B34683247.436098192;dc_trk_aid=628756331;dc_trk_cid=246436096;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;ltd=;dc_tdv=1?utm_source=tiktok&utm_medium=paid'},
   {'CreateTime': '2025-12-27 16:36:31',
    'AdTitle': 'Costco Same-Day',
    'AdLink': 'https://sameday.costco.com/?next=%2Fstore%2Fcostco%2Fproducts%2F82312501-huggies-natural-care-wipes&ttclid=E_C_P_Ct4BaQFFvS_JTI5a0grv4QoLx4TEBe5K--pK0PFOFKe9zFF1ofX7o6FaLVXxc9O3fE6jwPWP0dowH5c-m5-dC4FdKO7t4gcKf4QrxOA8D75wLkpsz5sLtUD4v_C4Ue_UCwpF4enEx8hBVWJpbbFdjO5JgIhrvAQN8DHJr22rZWCZ2EifS87yxBT62vHbygqX9iS016de4AFt1_WUykkchgCsw72EajJDHmhSuGhGrsUuVwCC8Wnl8IHTLOUrKiYLfrGDAsmZJ_D3GGYBdVkaYpu7XovAKyDeXBG4UxftSvusEgR2Mi4w'},
   {'CreateTime': '2025-12-28 22:06:15',
    'AdTitle': 'N/A',
    'AdLink': 'https://buy.angryorchard.com/social/665f3e40e859360f0f952fdc?utm_source=TikTok&utm_medium=paid_social&utm_campaign=25_Q4OD_BID_AOD_A2144_1_IMP_AOALW_129_CrispAppleReachQ4&utm_term=SOC_DIR_AOD_CRS_TTP_SOC_TKTOK_NAO_BHV_2TTI_OccasionalRebel_CCPM_S_CDCM_NIAS_NNLS_N000&utm_content=25_AODCA_TTV_5S4_DGA_SurpriseParty_E_NST_AO_AOALW_N&utm_placement=In_Feed&utm_marketing_tactic=Awareness&utm_id=1844179464139810&utm_placementid=1844179464139826&utm_creativeid=1844179464141842&ttclid=E_C_P_CtcBXCaIB-8MsUYjrPOc3UkqHH6btVFUG32nnTJDZFooiQErUGMt3Y_gd8ZhvzlKSoI4uZHBZcueJ-27B67WaeWVSPDZ-7az6XsuXVZ4C7ggDm4UHrSGEtI9NUr3S63gmck4SVuUZbxuHgEOhjDXP1nx-1uom01xnSOOb_HC20dZLbamLvsWJuTUhuW0V1BHDWwUZuhRFGUBPzd3zoGlKAKL5yF7M70hgVHRUDxXDD2pJaUuOCPpTefO7qQN--rjor7FfRVldlRLeYNhrYCnkS3pFGnylneO6V4SBHYyLjA'},
   {'CreateTime': '2025-12-29 18:44:03',
    'AdTitle': 'N/A',
    'AdLink': 'https://www.linzess.com/why-linzess/how-linzess-can-help?cid=scl_CV6dcc5b48a8f24054ae91b4fc47cf3ec2&ttclid=E_C_P_Ct4BJ-cx0ALauSm3KKzWNFTIprGEM60GWwuTssXWQ6-I0xF5t5xYyj_PQ-3x1Mu3erLeqsn-fmnAwx4ddVpQglr-6GgpPpn8q3fZcbMDmJ-mo8feQBm23qHRzrXLTKaOr1vJDWyHGq16Arkm0oreqrNEriT8zVpqEEVnTjgTf86QUXJA4VSCCEJ7nZrAuksxr-CO5yxW9u5tE8VvITO0n55V5P6z8DBFcrW3PsTF9cPLcX83QtQQAPerdabaZY2DD94Ocqyq504YwsblTDtoRredbZ2hE6fGMZD3DhruHViUEgR2Mi4w'},
   {'CreateTime': '2025-12-31 05:17:03',
    'AdTitle': 'Vaccines at CVS - Schedule Your Vaccine Appointment Online',
    'AdLink': 'https://www.cvs.com/immunizations/get-vaccinated?cid=sm_flu_hf&ttclid=E_C_P_Ct4BlMvtVuBKV_i0QGS3nL-0x0Cg6EoPQRH-Q0P9gZNg3F25f0PvNFHVI7_N4zdGFhKatFhg1ZdJTz8fX51hM-TzVT_forMZ1yOhVdwYmFXwZIlj9XM5r-JhzsKQ3XEFWNXLITrld10l5NVofSeVhthHrbN4bP-bJQz5L1CrEIMs2ZwBEzVdcObC4I2tQQ7kv35ihCoqehMpmMKBON1gbyU2asc6_fbtcCt3FTxMgzpojxyTqDcZNsDShwj_K2bct7hTLDk12HrLML5GgiZHTSUVhdA8CGoM4OTArnuBtJ-3EgR2Mi4w'},
   {'CreateTime': '2026-01-07 02:56:29',
    'AdTitle': 'Solovey Kitchen',
    'AdLink': 'https://soloveykitchen.com?utm_source=tiktok&utm_medium=paid&utm_id=1846061611178034&utm_campaign=Manual%20Campaign%20%7C%20Test%20Run&ttclid=E_C_P_CuABoLOemKQh0GiZS0K7gY62gYJBys-hqoGA6yGjStdTCSB2rLBV8clsAO7625dXMFc9MSgLhicsLS0KMoiFARLn7pWPlflu38_hwolOMpCmC17hiugufwSTYiTDX3H6J9sF_3NaVZyKLvCOp4HJGyjvkpHjt5Xlzijx1qmj7eCM9PSi0bXqXxEvGybb_gmqoGhi8CHDQ1msDbq7qORyXwDFgpWwyhiGr7rxW2SEYempojFUfMqc77gelXyZw-WWse5-UwqAnsO4cQ5P_E8jgBLFcQClBsi7BkAkphD9g5cegkMSBHYyLjA'},
   {'CreateTime': '2026-01-18 01:06:30',
    'AdTitle': 'Game Changer - Dropout',

In [157]:
len(tiktok["Your Activity"])

15

In [158]:
df_tiktok = pd.DataFrame(tiktok["Your Activity"])
df_tiktok.head()

,Ad Interests,Ads Visit History,Donation,Fundraiser,Hashtag,Instant Form Ads Responses,Login History,Off TikTok Activity,Purchases,Reposts,Searches,Share History,Status,Stickers,Watch History
AdInterestCategories,",",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AdsVisitHistoryList,NaN,"[{'CreateTime': '2025-11-08 15:32:14', 'AdTitl...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DonationList,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FundraiserList,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HashtagList,NaN,NaN,NaN,NaN,"[{'HashtagName': 'rupaul', 'HashtagLink': 'htt...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [159]:
len(df_tiktok)

16

In [160]:
df_tiktok

,Ad Interests,Ads Visit History,Donation,Fundraiser,Hashtag,Instant Form Ads Responses,Login History,Off TikTok Activity,Purchases,Reposts,Searches,Share History,Status,Stickers,Watch History
AdInterestCategories,",",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AdsVisitHistoryList,NaN,"[{'CreateTime': '2025-11-08 15:32:14', 'AdTitl...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DonationList,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FundraiserList,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HashtagList,NaN,NaN,NaN,NaN,"[{'HashtagName': 'rupaul', 'HashtagLink': 'htt...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ResponsesList,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LoginHistoryList,NaN,NaN,NaN,NaN,NaN,NaN,"[{'Date': '2024-12-26 00:01:54', 'IP': '75.38....",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OffTikTokActivityDataList,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'TimeStamp': '2025-11-28 19:30:19', 'Source'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
SendGifts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'SendGifts': None},NaN,NaN,NaN,NaN,NaN,NaN
BuyGifts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'BuyGifts': None},NaN,NaN,NaN,NaN,NaN,NaN
RepostList,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'Date': '2026-03-20 03:25:41', 'Link': 'http...",NaN,NaN,NaN,NaN,NaN
SearchList,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'Date': '2026-03-20 00:41:44', 'SearchTerm':...",NaN,NaN,NaN,NaN
ShareHistoryList,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'Date': '2025-09-21 00:05:18', 'SharedConten...",NaN,NaN,NaN
Status List,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'Resolution': '1320*2868', 'App Version': '4...",NaN,NaN
StickerList,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VideoList,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'Date': '2026-03-20 12:33:12', 'Link': 'http..."

In [161]:
df_tiktok['Searches'].iloc[11]

[{'Date': '2026-03-20 00:41:44', 'SearchTerm': 'Papa Giannopoulos'},
 {'Date': '2026-03-18 14:00:08', 'SearchTerm': 'City pop'},
 {'Date': '2026-03-18 02:02:02',
  'SearchTerm': 'lemon chicken cheesecake factory'},
 {'Date': '2026-03-18 00:20:52', 'SearchTerm': 'Shawn Dalton'},
 {'Date': '2026-03-16 03:36:43', 'SearchTerm': 'Kyle Bee'},
 {'Date': '2026-03-16 03:25:19', 'SearchTerm': 'olliebollen'},
 {'Date': '2026-03-16 01:29:14', 'SearchTerm': 'azazie becka dress'},
 {'Date': '2026-03-16 00:40:49', 'SearchTerm': 'gavin newsom vs barack obama'},
 {'Date': '2026-03-15 21:36:58', 'SearchTerm': 'Cinnamon azazie color'},
 {'Date': '2026-03-15 21:36:52', 'SearchTerm': 'Cinnamon paprika color'},
 {'Date': '2026-03-15 21:35:31', 'SearchTerm': 'azazie paprika color'},
 {'Date': '2026-03-15 15:44:17', 'SearchTerm': 'city'},
 {'Date': '2026-03-15 15:44:01', 'SearchTerm': 'My city'},
 {'Date': '2026-03-15 04:15:27', 'SearchTerm': 'Leaked labs'},
 {'Date': '2026-03-15 04:14:23', 'SearchTerm': 'thelipsticklesbians'},
 {'Date': '2026-03-13 03:13:05', 'SearchTerm': 'revolving door dance hotel'},
 {'Date': '2026-03-12 02:16:58', 'SearchTerm': 'jimmy love is blind'},
 {'Date': '2026-03-12 02:10:27',
  'SearchTerm': 'maya kibble and jonas brothers'},
 {'Date': '2026-03-11 18:17:31', 'SearchTerm': 'Wendy'},
 {'Date': '2026-03-11 18:14:45', 'SearchTerm': 'no pigeons'},
 {'Date': '2026-03-11 03:49:19', 'SearchTerm': 'repairing nervous system'},
 {'Date': '2026-03-11 03:47:56', 'SearchTerm': 'thelipsticklesbians drama'},
 {'Date': '2026-03-09 14:34:08', 'SearchTerm': 'traderjoestalia'},
 {'Date': '2026-03-08 04:14:55', 'SearchTerm': 'kylie and jackie o'},
 {'Date': '2026-03-08 03:12:38', 'SearchTerm': 'asteria halter top meshki'},
 {'Date': '2026-03-08 03:09:42', 'SearchTerm': 'Eichhörnchen'},
 {'Date': '2026-03-07 00:07:51', 'SearchTerm': "trader joe's vegetarian"},
 {'Date': '2026-03-05 20:38:56', 'SearchTerm': 'Rally funked'},
 {'Date': '2026-03-05 19:20:37', 'SearchTerm': 'pokemon wizard guys'},
 {'Date': '2026-03-02 03:24:55', 'SearchTerm': 'nick mohammed jurassic park'},
 {'Date': '2026-03-01 00:46:29', 'SearchTerm': 'carolyn bessette style'},
 {'Date': '2026-02-28 21:20:37', 'SearchTerm': 'oliver pratt movies'},
 {'Date': '2026-02-28 13:20:33', 'SearchTerm': 'Vegetarian costco'},
 {'Date': '2026-02-28 13:00:44', 'SearchTerm': 'Vegetarian costco'},
 {'Date': '2026-02-26 12:15:33', 'SearchTerm': 'Little French Bakery'},
 {'Date': '2026-02-24 02:46:49', 'SearchTerm': 'Jenny Wren'},
 {'Date': '2026-02-22 23:30:06', 'SearchTerm': 'the ham goblin'},
 {'Date': '2026-02-22 15:35:25', 'SearchTerm': 'ken and cheryl'},
 {'Date': '2026-02-21 20:43:32', 'SearchTerm': 'marysibande'},
 {'Date': '2026-02-20 23:10:46', 'SearchTerm': 'lil abner outfit'},
 {'Date': '2026-02-20 01:23:58', 'SearchTerm': 'evan papier original meme'},
 {'Date': '2026-02-18 12:27:22', 'SearchTerm': 'Eteri'},
 {'Date': '2026-02-16 21:45:02', 'SearchTerm': '7 brew cookie butter'},
 {'Date': '2026-02-16 04:25:29', 'SearchTerm': 'daddydaughter'},
 {'Date': '2026-02-16 00:26:32', 'SearchTerm': 'disney wish vegetarian food'},
 {'Date': '2026-02-16 00:26:17', 'SearchTerm': 'disney world vegetarian food'},
 {'Date': '2026-02-16 00:19:56', 'SearchTerm': 'Disney wish food'},
 {'Date': '2026-02-14 20:29:44', 'SearchTerm': 'disney wish activities'},
 {'Date': '2026-02-14 20:22:20', 'SearchTerm': 'disney wish tequlia tasting'},
 {'Date': '2026-02-14 20:22:12', 'SearchTerm': 'disney wish tequlia tasting'},
 {'Date': '2026-02-14 20:19:39',
  'SearchTerm': 'disney wish activities to book'},
 {'Date': '2026-02-14 20:19:18', 'SearchTerm': 'disney wish activities'},
 {'Date': '2026-02-14 20:17:10', 'SearchTerm': 'disney wish activities'},
 {'Date': '2026-02-14 20:10:51', 'SearchTerm': 'disney wish verandah room'},
 {'Date': '2026-02-14 16:39:50', 'SearchTerm': 'rae dunn in real life'},
 {'Date': '2026-02-14 13:44:30', 'SearchTerm': 'Elhoffer'},
 {'Date': '2026-02-14 04:28:01', 'SearchTerm': 'jeremy collins'},
 {'Date': '2026-02-14 00:21:32', 'SearchTerm': 'amandafrances'},
 {'Date': '2026-02-13 22:11:50', 'SearchTerm': 'gabi dress house of cb'},
 {'Date': '2026-02-13 04:37:24', 'SearchTerm': 'yuna Kim'},
 {'Date': '2026-02-12 22:36:35', 'SearchTerm': 'The Key of Awesome'},
 {'Date': '2026-02-12 03:31:57', 'SearchTerm': 'Disney wish food'},
 {'Date': '2026-02-11 01:50:06', 'SearchTerm': 'i aint china tiwan'},
 {'Date': '2026-02-11 01:49:41', 'SearchTerm': 'i aint china'},
 {'Date': '2026-02-08 14:07:19', 'SearchTerm': 'Kalemart24'},
 {'Date': '2026-02-08 03:32:41', 'SearchTerm': 'Banfield'},
 {'Date': '2026-02-07 14:02:35',
  'SearchTerm': 'mikayla nogueira lemme purr supplements'},
 {'Date': '2026-02-07 13:59:18', 'SearchTerm': 'disney world vi'},
 {'Date': '2026-02-06 20:48:24', 'SearchTerm': 'teamusa'},
 {'Date': '2026-02-06 12:43:11', 'SearchTerm': 'kid speaking robot'},
 {'Date': '2026-02-05 03:33:34', 'SearchTerm': 'preschool power 90s'},
 {'Date': '2026-02-04 03:41:58', 'SearchTerm': 'Competence warmth matrix'},
 {'Date': '2026-02-03 04:43:42', 'SearchTerm': 'ilia malinin minion'},
 {'Date': '2026-01-28 12:37:41', 'SearchTerm': 'derek hough coach jackie'},
 {'Date': '2026-01-28 12:35:43', 'SearchTerm': 'quad and gizelle wwhl clip'},
 {'Date': '2026-01-23 12:29:09', 'SearchTerm': 'viral trash can costco'},
 {'Date': '2026-01-22 04:09:49', 'SearchTerm': 'Shay spence poolside cruise'},
 {'Date': '2026-01-22 04:09:38', 'SearchTerm': 'Shay spence poolside'},
 {'Date': '2026-01-22 04:08:18', 'SearchTerm': 'Shay spence'},
 {'Date': '2026-01-22 03:27:29', 'SearchTerm': 'ORANGE MOCHA FRAPPUCCINO'},
 {'Date': '2026-01-21 19:51:38', 'SearchTerm': 'dr will rhap'},
 {'Date': '2026-01-21 03:48:31', 'SearchTerm': 'YOURE IN THE SHOT NOAH'},
 {'Date': '2026-01-20 00:01:02', 'SearchTerm': 'kimzolciak'},
 {'Date': '2026-01-19 15:21:40', 'SearchTerm': 'jlo glambot makeup'},
 {'Date': '2026-01-19 13:55:50', 'SearchTerm': 'zennioptical'},
 {'Date': '2026-01-17 04:39:14', 'SearchTerm': 'Madeleine White Fedyk'},
 {'Date': '2026-01-17 03:49:56', 'SearchTerm': 'what is a pucci outfit'},
 {'Date': '2026-01-15 22:25:15', 'SearchTerm': 'La Femme en Noir'},
 {'Date': '2026-01-15 04:04:24', 'SearchTerm': 'darshen'},
 {'Date': '2026-01-14 17:13:12', 'SearchTerm': 'how you get this job'},
 {'Date': '2026-01-14 13:43:51', 'SearchTerm': 'asscher cut engagement ring'},
 {'Date': '2026-01-14 13:20:55',
  'SearchTerm': 'samantha and david catfished bbc p2'},
 {'Date': '2026-01-10 03:23:37',
  'SearchTerm': 'barnes and noble valentines 2026 bow tote'},
 {'Date': '2026-01-09 05:55:30',
  'SearchTerm': 'sherry youre chinese horse yesr'},
 {'Date': '2026-01-09 05:54:50', 'SearchTerm': 'sherry youre chinese'},
 {'Date': '2026-01-08 18:21:24', 'SearchTerm': 'TURDY LOU FREEBUSH'},
 {'Date': '2026-01-08 03:54:08', 'SearchTerm': 'Tundra time'},
 {'Date': '2026-01-07 16:00:35',
  'SearchTerm': 'dear sean original video suzanne momchats'},
 {'Date': '2026-01-07 02:56:13', 'SearchTerm': 'Kent ohio food'},
 {'Date': '2026-01-06 01:13:22', 'SearchTerm': 'becca bloom crash out'},
 {'Date': '2026-01-05 16:31:59', 'SearchTerm': 'menorah guy'},
 {'Date': '2026-01-05 14:27:32', 'SearchTerm': 'hudson william'},
 {'Date': '2026-01-04 17:13:16', 'SearchTerm': 'Justin Hurwitz'},
 {'Date': '2026-01-04 14:49:15', 'SearchTerm': 'amybeth mcnulty'},
 {'Date': '2026-01-03 22:23:32',
  'SearchTerm': 'ginger minj lying ruby slippers'},
 {'Date': '2026-01-03 22:08:41',
  'SearchTerm': 'nicole avant and ted sarandos'},
 {'Date': '2025-12-30 05:21:30', 'SearchTerm': 'aceos'},
 {'Date': '2025-12-30 05:20:08', 'SearchTerm': 'jamesholzhauer'},
 {'Date': '2025-12-29 22:39:03', 'SearchTerm': 'Scotland'},
 {'Date': '2025-12-29 22:30:22', 'SearchTerm': 'wildcurves paper doll top'},
 {'Date': '2025-12-29 04:53:11',
  'SearchTerm': 'kate steinburg and chad reality tv show'},
 {'Date': '2025-12-28 21:00:23',
  'SearchTerm': 'rachel and meghan variety show'},
 {'Date': '2025-12-28 01:51:26', 'SearchTerm': 'Jackie D'},
 {'Date': '2025-12-27 21:15:46', 'SearchTerm': 'cheese and chapati'},
 {'Date': '2025-12-27 13:55:41', 'SearchTerm': 'what is cholestasis'},
 {'Date': '2025-12-27 13:55:10', 'SearchTerm': 'rusty betmgm review'},
 {'Date': '2025-12-26 14:58:39', 'SearchTerm': 'Saudi Arabia Fashion'},
 {'Date': '2025-12-26 14:34:25', 'SearchTerm': 'gracie abrams screenshot'},
 {'Date': '2025-12-26 02:56:03', 'SearchTerm': 'car salesman 900 credit'},
 {'Date': '2025-12-25 00:12:25', 'SearchTerm': '90 day fiance birkan'},
 {'Date': '2025-12-24 04:34:08',
  'SearchTerm': 'buxton bag commercial milk butter eggs'},
 {'Date': '2025-12-24 03:34:40', 'SearchTerm': 'Isabel Klee'},
 {'Date': '2025-12-24 03:02:24', 'SearchTerm': 'sheku kanneh mason'},
 {'Date': '2025-12-24 02:59:50', 'SearchTerm': 'hello water bottle video'},
 {'Date': '2025-12-23 18:47:01', 'SearchTerm': 'Raise Your Voice'},
 {'Date': '2025-12-23 17:02:17', 'SearchTerm': 'chilaquiles recipes'},
 {'Date': '2025-12-21 15:07:43', 'SearchTerm': 'trust coffee co'},
 {'Date': '2025-12-20 16:53:03',
  'SearchTerm': 'paul thomas anderson maya rudolph'},
 {'Date': '2025-12-17 03:30:35', 'SearchTerm': 'chris fleming'},
 {'Date': '2025-12-15 23:12:56', 'SearchTerm': 'hannah brown new video'},
 {'Date': '2025-12-14 15:56:52',
  'SearchTerm': 'move 1 pencil to make 3 triangle answer'},
 {'Date': '2025-12-14 01:45:44', 'SearchTerm': 'kizik boots'},
 {'Date': '2025-12-12 12:34:32', 'SearchTerm': 'what is a sophie scarf'},
 {'Date': '2025-12-12 01:49:42', 'SearchTerm': 'samyra parking meter'},
 {'Date': '2025-12-10 12:06:26',
  'SearchTerm': 'jewish mother fashion emergency'},
 {'Date': '2025-12-09 21:31:27', 'SearchTerm': 'solidcore flip out'},
 {'Date': '2025-12-07 15:21:58', 'SearchTerm': 'madeline hmart soogia'},
 {'Date': '2025-12-07 03:00:48', 'SearchTerm': 'Zoella advent calendar'},
 {'Date': '2025-12-06 21:09:04',
  'SearchTerm': 'mckenna grace and josh hutcherson interview'},
 {'Date': '2025-12-06 21:07:27', 'SearchTerm': 'arc bag'},
 {'Date': '2025-12-06 21:06:59', 'SearchTerm': 'arc bag'},
 {'Date': '2025-12-06 02:10:40', 'SearchTerm': 'broma bakery cookie'},
 {'Date': '2025-12-06 02:10:30', 'SearchTerm': 'Cowboy cookies'},
 {'Date': '2025-12-05 17:36:28', 'SearchTerm': 'preserved coconut husk'},
 {'Date': '2025-12-01 04:21:11', 'SearchTerm': 'the bishops school peptalk'},
 {'Date': '2025-11-30 23:49:18', 'SearchTerm': 'Laina Rauma shorts'},
 {'Date': '2025-11-30 17:07:38',
  'SearchTerm': 'wrapping gifts as something else tutorial'},
 {'Date': '2025-11-30 04:22:15',
  'SearchTerm': 'wherever i go my cousin goes dez and troy'},
 {'Date': '2025-11-29 19:19:53', 'SearchTerm': 'how to potty train puppy'},
 {'Date': '2025-11-29 12:57:25',
  'SearchTerm': 'spongebob big guy pants okay jennxpenn'},
 {'Date': '2025-11-27 13:26:24', 'SearchTerm': 'usa 2026 jerseys'},
 {'Date': '2025-11-27 13:09:32', 'SearchTerm': 'parke sweaters'},
 {'Date': '2025-11-26 22:47:08', 'SearchTerm': 'the white rabbit'},
 {'Date': '2025-11-26 21:17:27', 'SearchTerm': 'bodythrob'},
 {'Date': '2025-11-26 03:35:31',
  'SearchTerm': 'poseidon green sherwin williams'},
 {'Date': '2025-11-26 02:25:59', 'SearchTerm': 'flanderization bobs burgers'},
 {'Date': '2025-11-25 23:17:22', 'SearchTerm': 'puffer jacket new york'},
 {'Date': '2025-11-25 00:57:03', 'SearchTerm': 'dancing fruit for babies'},
 {'Date': '2025-11-24 01:52:47', 'SearchTerm': '200 1 line answer'},
 {'Date': '2025-11-23 04:27:50', 'SearchTerm': 'Hailee shallot di'},
 {'Date': '2025-11-23 04:26:31', 'SearchTerm': 'Girlala'},
 {'Date': '2025-11-23 01:17:21', 'SearchTerm': '5 minute tofu'},
 {'Date': '2025-11-22 13:45:47', 'SearchTerm': 'rag and bone sweat jeans'},
 {'Date': '2025-11-22 02:15:38', 'SearchTerm': 'liz and daniel dress'},
 {'Date': '2025-11-21 23:38:15', 'SearchTerm': 'vegan desserts'},
 {'Date': '2025-11-21 23:33:13', 'SearchTerm': 'vegan desserts thanksgiving'},
 {'Date': '2025-11-21 17:45:45',
  'SearchTerm': "Farewell To Mr. Marbles, Jenna Marbles' Dog"},
 {'Date': '2025-11-21 17:18:49',
  'SearchTerm': 'real housewives of salt lake city'},
 {'Date': '2025-11-21 01:42:39',
  'SearchTerm': 'robby hoffman sister emmys presenting'},
 {'Date': '2025-11-20 00:37:42', 'SearchTerm': 'Vegan stuffed mushrooms'},
 {'Date': '2025-11-19 17:25:40',
  'SearchTerm': 'top of the pyramid maddie meme'},
 {'Date': '2025-11-19 17:25:07', 'SearchTerm': 'top of the pyramid maddie'},
 {'Date': '2025-11-19 17:23:32', 'SearchTerm': 'top of the pyramids'},
 {'Date': '2025-11-19 02:38:46', 'SearchTerm': 'corinna fulgieri'},
 {'Date': '2025-11-18 02:19:55', 'SearchTerm': 'dinasourjr'},
 {'Date': '2025-11-17 21:28:49', 'SearchTerm': 'mary cosby lite girl'},
 {'Date': '2025-11-16 22:08:28', 'SearchTerm': 'kate spade hot dog ring'},
 {'Date': '2025-11-16 21:37:15', 'SearchTerm': 'Movement By David'},
 {'Date': '2025-11-16 21:03:03', 'SearchTerm': 'Haunted hathaways'},
 {'Date': '2025-11-16 02:55:47',
  'SearchTerm': 'betsey johnson fruit dress 2019'},
 {'Date': '2025-11-16 01:57:51', 'SearchTerm': 'glambot'},
 {'Date': '2025-11-16 01:54:08', 'SearchTerm': 'hannah krieg social media'},
 {'Date': '2025-11-15 12:41:02', 'SearchTerm': 'acuvue oasis twins'},
 {'Date': '2025-11-15 03:03:36', 'SearchTerm': 'yp3344 david bridal dress'},
 {'Date': '2025-11-12 03:05:16', 'SearchTerm': 'Kaelynn'},
 {'Date': '2025-11-12 03:05:11', 'SearchTerm': 'Kara Karp'},
 {'Date': '2025-11-11 02:07:30', 'SearchTerm': 'hutterite colony'},
 {'Date': '2025-11-11 01:23:04', 'SearchTerm': 'shiny bright ornaments'},
 {'Date': '2025-11-11 01:03:48', 'SearchTerm': 'pizza cruncher'},
 {'Date': '2025-11-11 00:45:50',
  'SearchTerm': 'jennifer lawrence making fun of lisa barlow'},
 {'Date': '2025-11-09 20:26:28',
  'SearchTerm': 'www.icloud.com/shortcuts/143a7ecfa43942a5a2aadbda47fd2449'},
 {'Date': '2025-11-09 20:26:20',
  'SearchTerm': 'www.icloud.com/shortcuts/143a7ecfa43942a5a2aadbda47fd2449'},
 {'Date': '2025-11-08 03:16:18', 'SearchTerm': 'ny post cover'},
 {'Date': '2025-11-07 01:15:22', 'SearchTerm': 'Sophocles'},
 {'Date': '2025-11-05 20:29:51', 'SearchTerm': 'Dieitian salsa'},
 {'Date': '2025-11-04 22:36:49', 'SearchTerm': 'marry me tofu'},
 {'Date': '2025-11-03 02:07:11', 'SearchTerm': 'the butch and the bimbo'},
 {'Date': '2025-11-03 00:01:40', 'SearchTerm': 'SPENCER BRESLIN'},
 {'Date': '2025-11-01 15:57:26', 'SearchTerm': '3d printed mask'},
 {'Date': '2025-11-01 01:07:58', 'SearchTerm': 'lisa barlow ankles'},
 {'Date': '2025-11-01 00:32:12',
  'SearchTerm': 'the substitute teacher that got fired strap'},
 {'Date': '2025-10-30 15:56:29', 'SearchTerm': 'italian brainrot'},
 {'Date': '2025-10-27 18:01:46', 'SearchTerm': 'gay ghost hunting'},
 {'Date': '2025-10-27 02:36:00', 'SearchTerm': 'cucumber salad'},
 {'Date': '2025-10-27 02:28:40', 'SearchTerm': 'vegetarian potluck ideas'},
 {'Date': '2025-10-25 21:27:40', 'SearchTerm': 'jan ravnik'},
 {'Date': '2025-10-25 15:28:15', 'SearchTerm': 'Madison Anne'},
 {'Date': '2025-10-23 11:56:22', 'SearchTerm': 'xbox'},
 {'Date': '2025-10-21 00:35:31', 'SearchTerm': 'Sofia Franklyn'},
 {'Date': '2025-10-13 01:26:38', 'SearchTerm': 'whats egl fashion'},
 {'Date': '2025-10-13 00:23:52',
  'SearchTerm': 'can we kiss forever by kina song'},
 {'Date': '2025-10-10 21:57:40', 'SearchTerm': 'tyler chase neds classified'},
 {'Date': '2025-10-09 17:34:01',
  'SearchTerm': 'running away with abortion sign'},
 {'Date': '2025-10-09 17:33:36', 'SearchTerm': 'abortion sign ran away'},
 {'Date': '2025-10-09 02:31:01', 'SearchTerm': 'the turtle kids'},
 {'Date': '2025-10-09 00:41:09', 'SearchTerm': 'disneylandcalifornia'},
 {'Date': '2025-10-08 01:52:53', 'SearchTerm': 'Cassada cake'},
 {'Date': '2025-10-07 05:41:06', 'SearchTerm': 'Elisabeth Hasselbeck'},
 {'Date': '2025-10-07 05:40:22', 'SearchTerm': 'Elisabeth Hasselbeck'},
 {'Date': '2025-10-03 23:32:54',
  'SearchTerm': 'woman dancing aggressively white woman'},
 {'Date': '2025-10-03 23:32:44', 'SearchTerm': 'woman dancing aggressively'},
 {'Date': '2025-10-03 23:32:14',
  'SearchTerm': 'fast paced dance meme white woman'},
 {'Date': '2025-10-03 23:32:02', 'SearchTerm': 'fast paced audio'},
 {'Date': '2025-10-03 23:31:52', 'SearchTerm': 'fast paced dance meme'},
 {'Date': '2025-10-02 06:03:14', 'SearchTerm': 'abby jimenez stuntman mike'},
 {'Date': '2025-10-02 06:01:00', 'SearchTerm': 'hayley williams josh farro'},
 {'Date': '2025-10-01 15:30:11', 'SearchTerm': 'thanks for unpausing hasan'},
 {'Date': '2025-09-29 02:20:38', 'SearchTerm': 'troye sivan wolverine'},
 {'Date': '2025-09-28 02:30:29', 'SearchTerm': 'Hannah Brown'},
 {'Date': '2025-09-25 20:43:15', 'SearchTerm': 'hugh jackman singing'},
 {'Date': '2025-09-25 20:10:16',
  'SearchTerm': 'fish monger halloween costume'},
 {'Date': '2025-09-25 01:43:04', 'SearchTerm': 'weddinganniversary'},
 {'Date': '2025-09-24 18:47:38', 'SearchTerm': 'dean'},
 {'Date': '2025-09-24 18:10:44', 'SearchTerm': 'white house account'},
 {'Date': '2025-09-23 18:19:54',
  'SearchTerm': 'what is the relationship between ian and jessica the chef'},
 {'Date': '2025-09-23 18:06:32', 'SearchTerm': 'chaggachino'},
 {'Date': '2025-09-23 18:05:49', 'SearchTerm': 'chaggachino'},
 {'Date': '2025-09-23 12:25:54', 'SearchTerm': 'hannah brown vacuum'},
 {'Date': '2025-09-23 12:25:47', 'SearchTerm': 'hannah brown vacuum'},
 {'Date': '2025-09-23 02:12:15',
  'SearchTerm': 'polyphonic perception original girl'},
 {'Date': '2025-09-23 01:28:00', 'SearchTerm': 'sabrina the vegan'},
 {'Date': '2025-09-22 01:41:25',
  'SearchTerm': 'polyphonic perception original girl'},
 {'Date': '2025-09-21 23:34:46', 'SearchTerm': 'kale couscous salad'},
 {'Date': '2025-09-21 23:34:35', 'SearchTerm': 'kale couscous chickpea salad'}]

In [162]:
len(df_tiktok['Searches'].iloc[11])

244

In [163]:
### df_tiktok['Share History'].iloc[12]

In [164]:
len(df_tiktok['Share History'].iloc[12])

3812

In [165]:
len(df_tiktok['Watch History'].iloc[15])

78194

In [166]:
### df_tiktok['Watch History'].iloc[15]

In [167]:
len(df_tiktok['Ad Interests'].iloc[0])

1

In [168]:
df_tiktok['Ad Interests'].iloc[0]

','

# Milestone 1 
So... I thought tidy data by milestone 1 was possible. BOY IT WAS NOT with my current skill set. So here's the NEW milestone: TIKTOK data is tidy. Webscraping will be crucial for the Instagram portion and... I'm going to wait until the lecture to make that happen. 
I've also refined my questions I'm hoping to answer within understanding how students use tiktok vs how they use Instagram.  
### First, what advertising terms/interests do each platform assign to them? 
What are the big terms within each platform? 
     Somehow this is NOT in your activity on Tiktok's downloadable data. "Ad interest" is in the data set but it's a COMMA? They just let you see it without having to download which is nice but it's NOT in the nice neat json file. So for this one I will need to add it the Tiktok Tidy Data Frame. 
### Second, Watch times, how do they differ between platforms? 
I'm HOPING this isn't a pain in the butt. 
Notes from convo with Dr. Silva: Date Time delta, PD.date 
### Third, Activity times 
 When are students most likely to be on which platform? 
Dates are nice but what would be the most helpful would be what day of the week is the most active on each platform? Bonus points for time of day. 
Notes from convo with Dr. Silva: New column, full date time, hour element 24 hour portion, aggrigate, day element, day element, Heat map, Look at Timestamp documentation for pandas, you can also Grab weekday vs weekend elements. Concat take all of these rows and add them. Git hub parsing, Large lanuage models to look for tools

In [169]:
with open("IG recommended_topics.html", encoding= "utf-8") as IGTopics: 
    ig_dat1 = BeautifulSoup(IGTopics.read(), "html.parser")

In [170]:
ig_dat1

<html><head><meta content="text/html; charset=utf-8" http-equiv="Content-Type"/><base href="../../"/><style nonce="1lSzB6Zr" type="text/css">html{touch-action:manipulation}body{background:#fff;color:#1c1e21;direction:ltr;line-height:1.34;margin:0;padding:0;unicode-bidi:embed}body,button,input,label,select,td,textarea{font-family:Helvetica,Arial,sans-serif;font-size:12px}h1,h2,h3,h4,h5,h6{color:#1c1e21;font-size:13px;font-weight:600;margin:0;padding:0}h1{font-size:14px}h4,h5,h6{font-size:12px}p{margin:1em 0}b,strong{font-weight:600}a{color:#385898;cursor:pointer;text-decoration:none}button{margin:0}a:hover{text-decoration:underline}img{border:0px}td,td.label{text-align:left}dd{color:#000}dt{color:#606770}ul{list-style-type:none;margin:0;padding:0}abbr{border-bottom:none;text-decoration:none}hr{background:#dadde1;border-width:0;color:#dadde1;height:1px}
form{margin:0;padding:0}label{color:#606770;cursor:default;font-weight:600;vertical-align:middle}label input{font-weight:400}textarea,.inputtext,.inputpassword{border:1px solid #CCD0D5;border-radius:0;margin:0;padding:3px}textarea{max-width:100%}select{border:1px solid #CCD0D5;padding:2px}input,select,textarea{background-color:#fff;color:#1c1e21}.inputtext,.inputpassword{padding-bottom:4px}.inputtext:invalid,.inputpassword:invalid{box-shadow:none}.inputradio{margin:0 5px 0 0;padding:0;vertical-align:middle}.inputcheckbox{border:0;vertical-align:middle}.inputbutton,.inputsubmit{background-color:#4267b2;border-color:#DADDE1 #0e1f5b #0e1f5b #d9dfea;border-style:solid;border-width:1px;color:#fff;padding:2px 15px 3px;text-align:center}.inputaux{background:#ebedf0;border-color:#EBEDF0 #666 #666 #e7e7e7;color:#000}.inputsearch{background:#fff url(https://static.xx.fbcdn.net/rsrc.php/v4/yB/r/xwZ-58W7La1.png) no-repeat left 4px;padding-left:17px}
.clearfix:after{clear:both;content:".";display:block;font-size:0;height:0;line-height:0;visibility:hidden}.datawrap{word-wrap:break-word}.word_break{display:inline-block}.ellipsis{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.aero{opacity:.5}.column{float:left}.center{margin-left:auto;margin-right:auto}#facebook .hidden_elem{display:none!important}#facebook .invisible_elem{visibility:hidden}#facebook .accessible_elem{clip:rect(1px,1px,1px,1px);height:1px;overflow:hidden;position:absolute;white-space:nowrap;width:1px}#facebook .accessible_elem_offset{margin:-1px}.direction_ltr{direction:ltr}.direction_rtl{direction:rtl}.text_align_ltr{text-align:left}.text_align_rtl{text-align:right}
body{overflow-y:scroll}.mini_iframe{overflow-y:visible}.auto_resize_iframe{height:auto;overflow:hidden}#content{margin:0;outline:none;padding:0;width:auto}.UIStandardFrame_Container{margin:0 auto;padding-top:20px;width:960px}.UIStandardFrame_Content{float:left;margin:0;padding:0;width:760px}.UIStandardFrame_SidebarAds{float:right;margin:0;padding:0;width:200px;word-wrap:break-word}.UIFullPage_Container{margin:0 auto;padding:20px 12px 0;width:940px}.standard_status_element{visibility:hidden}.standard_status_element.async_saving{visibility:visible}svg{forced-color-adjust:auto}img.tracking_pixel{height:1px;position:absolute;visibility:hidden;width:1px}
#globalContainer{margin:0 auto;position:relative}.fbx #globalContainer{width:981px}.sidebarMode #globalContainer{padding-right:205px}.fbx #tab_canvas>div{padding-top:0}.fb_content{min-height:640px;padding-bottom:20px}.fbx .fb_content{padding-bottom:0}.skipto{display:none}.home .skipto{display:block}
._li._li._li{overflow:initial}._aj3e,._aj3e video{display:block;height:4px;left:0;position:absolute;top:0;width:2px;z-index:-1}._aowd._li._li._li{overflow:hidden}._9053 ._li._li._li{overflow-x:hidden}._72b0{position:relative;z-index:0}.registration ._li._9bpz{background-color:#f0f2f5}._li ._9bp-{padding-top:5px;text-align:center}._li ._9bp- .fb_logo{height:100px}._li ._a66f{padding-top:5px;text-align:center}._li ._a66f .fb_logo{height:80px;padding-top:72px}
._5vb_ #pageFooter{display:none}html body._5vb_ #globalContainer{width:976px}._5vb_.hasLeftCol #headerArea{margin:0;padding-top:0;width:786px}._5vb_,._5vb_ #contentCol{background-color:#e9ebee;color:#1d2129}html ._5vb_.hasLeftCol #contentCol{border-left:0;margin-left:172px;padding-left:11px;padding-top:11px}._5vb_.hasLeftCol #topNav{border-left:0;margin-left:172px;padding:11px 7px 0 11px}._5vb_.hasLeftCol #topNav~#contentCol{padding-top:0}._5vb_.hasLeftCol #leftCol{padding-left:8px;padding-top:12px;width:164px}._5vb_.hasLeftCol #mainContainer{border-right:0;margin-left:0}._5vb_.hasLeftCol #pageFooter{background:none}html ._5vb_._5vb_.hasLeftCol div#contentArea{padding-left:0;padding-right:10px;width:786px}html ._5vb_._5vb_.hasLeftCol .hasRightCol div#contentArea{width:496px}._5vb_.hasLeftCol ._5r-_ div#rightCol{padding:0 7px 0 0;width:280px}
._2yq #globalContainer{width:1012px!important}@media (min-width: 1000px) and (max-width: 1013px){._2yq._2yq._2yq>div:first-child{overflow-x:hidden}}._2yq #headerArea{float:none!important;padding:0 0 12px!important;width:auto!important}._2yq #contentArea{margin-right:0;padding:0!important}._2yq #leftCol,._2yq #contentCol{padding:0!important}._2yq #rightCol{float:left;margin-top:0;padding:0!important}.tinyViewport ._2yq #pagelet_navigation.fixed_elem{position:static!important}._2yq .loggedout_menubar_container{min-width:1014px}@media (min-width: 1014px){._2yq .loggedout_menubar{width:1014px}}
._a7o5{font-size:15px;margin:auto}._a705{margin:0 auto;max-width:800px;width:100%}._ap67{max-width:none}._a706{margin-bottom:15px;position:relative;width:inherit;word-break:break-word;z-index:0}._a707{clear:both;color:#7f7f7f;margin-bottom:20px;margin-top:10px;text-align:center}._a70a,._a70b,._a709{background:#fff;border-radius:8px;display:flex;flex-direction:row;margin-bottom:20px;margin-top:12px;padding:15px}._a70a,._a70b{border-radius:3px;padding-left:2px}._as-_{margin-bottom:8px}._ap67 ._as-_{margin-bottom:24px}._a70c{border-radius:50%;height:16px;padding:4px;width:16px}._a70d{margin-left:8px;width:100%}._a70d>h1{color:#1d2129;font-size:100%;font-weight:700;line-height:18px;padding-bottom:3px}._a70d>p._aoa9:last-child{margin-bottom:3px}._asyh{color:#1d2129;font-weight:700;line-height:18px;padding-bottom:3px}._aoa9{color:#1d2129;line-height:16px;margin-bottom:9px;margin-top:6px}._aoaa{color:#90949c;line-height:16px;margin-top:6px}._a70f{color:#90949c;line-height:16px;margin:0}._as10{color:#90949c;line-height:16px;margin:6px 0 0}._a70h{margin-top:4px}._as_0{height:55px;left:0;position:fixed;right:0;top:0;z-index:99}._as_0+div{margin-top:56px}._a7cj{background:#fff;box-shadow:0 1px 7px #ccc;position:fixed;width:100%;z-index:99}._acpq{background:#fff;border-radius:8px;margin-top:15px;padding:10px}._acpr{font-weight:700;margin-bottom:3px}._a7co{margin-left:16px}._a7cv{align-items:center;display:flex;justify-content:end}._a7cw{align-items:center;display:flex;margin-right:16px}._a7cx{border-radius:50%;margin-right:8px}._a7cy{font-size:15px;font-weight:600}._a7cz{margin-left:8px;margin-right:16px}._a7c-{color:#000;text-decoration:none}._a7c_{height:70px;width:100%}._alz_{background:#fff;border-radius:8px;border-spacing:0px;table-layout:fixed;text-align:left;width:100%}._alz_>thead>tr:first-child{position:sticky;top:0}._alz_>thead>tr>*{background-color:#f0f2f5;padding:16px 12px;width:150px}._alz_>thead>tr>td{color:#444950}._alz_>tbody>tr>td{border-top:1px solid #F4FAFF;padding:16px 12px}._ar4w{list-style-position:inside;list-style-type:disc;margin-left:12px;margin-top:12px}
._a6-g{background:#fff;border-radius:8px}main>._a6-g{margin-bottom:8px}._a6-h{color:#1d2129;font-weight:700;line-height:18px}._a6-i{border-bottom:1px solid #DADDE1}section._a6-g h2{font-size:100%;font-weight:700;line-height:18px}._a6-o,._a6-o a{color:#8d949e;line-height:16px}._a72d{padding-bottom:12px;padding-left:12px;padding-right:12px}._a6-p{color:#1d2129;line-height:17px}._a6-q{color:gray}._a6_m{font-weight:700}._a6_n{line-height:2;text-align:left}._a6_n tbody tr th{padding:5px;text-align:left;vertical-align:top;width:150px}._a6_o{max-width:100%}._a6_p{font-weight:700}._a6_q{color:#90949c;line-height:20px;min-width:50px}._a6_r{line-height:20px}._a7nf{display:flex;padding-left:5px;margin-bottom:5px}._a7ng{padding-right:5px}._a7nh{width:20%}
._4jnw{margin:0}._3-8h{margin:4px}._3-8i{margin:8px}._3-8j{margin:12px}._3-8k{margin:16px}._3-8l{margin:20px}._2-5b{margin:24px}._1kbd{margin-bottom:0;margin-top:0}._3-8m{margin-bottom:4px;margin-top:4px}._3-8n{margin-bottom:8px;margin-top:8px}._3-8o{margin-bottom:12px;margin-top:12px}._3-8p{margin-bottom:16px;margin-top:16px}._3-8q{margin-bottom:20px;margin-top:20px}._2-ox{margin-bottom:24px;margin-top:24px}._1a4i{margin-left:0;margin-right:0}._3-8r{margin-left:4px;margin-right:4px}._3-8s{margin-left:8px;margin-right:8px}._3-8t{margin-left:12px;margin-right:12px}._3-8u{margin-left:16px;margin-right:16px}._3-8v{margin-left:20px;margin-right:20px}._6bu9{margin-left:24px;margin-right:24px}._5soe{margin-top:0}._3-8w{margin-top:4px}._3-8x{margin-top:8px}._3-8y{margin-top:12px}._3-8z{margin-top:16px}._3-8-{margin-top:20px}._4aws{margin-top:24px}._2-jz{margin-right:0}._3-8_{margin-right:4px}._3-90{margin-right:8px}._3-91{margin-right:12px}._3-92{margin-right:16px}._3-93{margin-right:20px}._y8t{margin-right:24px}._5emk{margin-bottom:0}._3-94{margin-bottom:4px}._3-95{margin-bottom:8px}._3-96{margin-bottom:12px}._3-97{margin-bottom:16px}._3-98{margin-bottom:20px}._20nr{margin-bottom:24px}._av_{margin-left:0}._3-99{margin-left:4px}._3-9a{margin-left:8px}._3-9b{margin-left:12px}._3-9c{margin-left:16px}._3-9d{margin-left:20px}._4m0t{margin-left:24px}._a82f{margin-left:28px}
._8tm{padding:0}._2phz{padding:4px}._2ph-{padding:8px}._2ph_{padding:12px}._2pi0{padding:16px}._2pi1{padding:20px}._40c7{padding:24px}._2o1j{padding:36px}._6buq{padding-bottom:0;padding-top:0}._2pi2{padding-bottom:4px;padding-top:4px}._2pi3{padding-bottom:8px;padding-top:8px}._2pi4{padding-bottom:12px;padding-top:12px}._2pi5{padding-bottom:16px;padding-top:16px}._2pi6{padding-bottom:20px;padding-top:20px}._2o1k{padding-bottom:24px;padding-top:24px}._2o1l{padding-bottom:36px;padding-top:36px}._6bua{padding-left:0;padding-right:0}._2pi7{padding-left:4px;padding-right:4px}._2pi8{padding-left:8px;padding-right:8px}._2pi9{padding-left:12px;padding-right:12px}._2pia{padding-left:16px;padding-right:16px}._2pib{padding-left:20px;padding-right:20px}._2o1m{padding-left:24px;padding-right:24px}._2o1n{padding-left:36px;padding-right:36px}._iky{padding-top:0}._2pic{padding-top:4px}._2pid{padding-top:8px}._2pie{padding-top:12px}._2pif{padding-top:16px}._2pig{padding-top:20px}._2owm{padding-top:24px}._div{padding-right:0}._2pih{padding-right:4px}._2pii{padding-right:8px}._2pij{padding-right:12px}._2pik{padding-right:16px}._2pil{padding-right:20px}._31wk{padding-right:24px}._2phb{padding-right:32px}._au-{padding-bottom:0}._2pim{padding-bottom:4px}._2pin{padding-bottom:8px}._2pio{padding-bottom:12px}._2pip{padding-bottom:16px}._2piq{padding-bottom:20px}._2o1p{padding-bottom:24px}._4gao{padding-bottom:32px}._1cvx{padding-left:0}._2pir{padding-left:4px}._2pis{padding-left:8px}._2pit{padding-left:12px}._2piu{padding-left:16px}._2piv{padding-left:20px}._2o1q{padding-left:24px}._2o1r{padding-left:36px}
.uiBoxGray{background-color:#f2f2f2;border:1px solid #ccc}.uiBoxDarkgray{color:#ccc;background-color:#333;border:1px solid #666}.uiBoxGreen{background-color:#d1e6b9;border:1px solid #629824}.uiBoxLightblue{background-color:#edeff4;border:1px solid #d8dfea}.uiBoxRed{background-color:#ffebe8;border:1px solid #dd3c10}.uiBoxWhite{background-color:#fff;border:1px solid #ccc}.uiBoxYellow{background-color:#fff9d7;border:1px solid #e2c822}.uiBoxOverlay{background:#ffffffd9;border:1px solid #3b5998;border:1px solid rgba(59,89,153,.65)}.uiBoxError{background-color:#ffe6e3;border:1px solid #DB4123}.uiBoxErrordark{background-color:#3d000a;border:1px solid #AA2312}.noborder{border:none}.topborder{border-bottom:none;border-left:none;border-right:none}.bottomborder{border-left:none;border-right:none;border-top:none}.dashedborder{border-style:dashed}
.pas{padding:5px}.pa8{padding:8px}.pam{padding:10px}.pa16{padding:16px}.pal{padding:20px}.pts{padding-top:5px}.pt8{padding-top:8px}.ptm{padding-top:10px}.pt16{padding-top:16px}.ptl{padding-top:20px}.prs{padding-right:5px}.pr8{padding-right:8px}.prm{padding-right:10px}.pr16{padding-right:16px}.prl{padding-right:20px}.pbs{padding-bottom:5px}.pb8{padding-bottom:8px}.pbm{padding-bottom:10px}.pb16{padding-bottom:16px}.pbl{padding-bottom:20px}.pls{padding-left:5px}.pl8{padding-left:8px}.plm{padding-left:10px}.pl16{padding-left:16px}.pll{padding-left:20px}.phs{padding-left:5px;padding-right:5px}.ph8{padding-left:8px;padding-right:8px}.phm{padding-left:10px;padding-right:10px}.ph16{padding-left:16px;padding-right:16px}.phl{padding-left:20px;padding-right:20px}.pvs{padding-top:5px;padding-bottom:5px}.pv8{padding-bottom:8px;padding-top:8px}.pvm{padding-top:10px;padding-bottom:10px}.pv16{padding-bottom:16px;padding-top:16px}.pvl{padding-top:20px;padding-bottom:20px}.mas{margin:5px}.ma8{margin:8px}.mam{margin:10px}.ma16{margin:16px}.mal{margin:20px}.mts{margin-top:5px}.mt8{margin-top:8px}.mtm{margin-top:10px}.mt16{margin-top:16px}.mtl{margin-top:20px}.mrs{margin-right:5px}.mr8{margin-right:8px}.mrm{margin-right:10px}.mr16{margin-right:16px}.mrl{margin-right:20px}.mbs{margin-bottom:5px}.mb8{margin-bottom:8px}.mbm{margin-bottom:10px}.mb16{margin-bottom:16px}.mbl{margin-bottom:20px}.mls{margin-left:5px}.ml8{margin-left:8px}.mlm{margin-left:10px}.ml16{margin-left:16px}.mll{margin-left:20px}.mhs{margin-left:5px;margin-right:5px}.mh8{margin-left:8px;margin-right:8px}.mhm{margin-left:10px;margin-right:10px}.mh16{margin-left:16px;margin-right:16px}.mhl{margin-left:20px;margin-right:20px}.mvs{margin-top:5px;margin-bottom:5px}.mv8{margin-bottom:8px;margin-top:8px}.mvm{margin-top:10px;margin-bottom:10px}.mv16{margin-bottom:16px;margin-top:16px}.mvl{margin-top:20px;margin-bottom:20px}

Well.. I'm not going to touch that just yet

In [171]:
tablett2= pd.DataFrame(df_tiktok['Watch History'].iloc[15])

In [172]:
tablett2.head()

                  Date                                               Link
0  2026-03-20 12:33:12  https://www.tiktokv.com/share/video/7616782825...
1  2026-03-20 12:32:59  https://www.tiktokv.com/share/video/7618946244...
2  2026-03-20 12:02:37  https://www.tiktokv.com/share/video/7619059457...
3  2026-03-20 12:02:36  https://www.tiktokv.com/share/video/7501170729...
4  2026-03-20 11:53:03  https://www.tiktokv.com/share/video/7618388640...

Okay here are the columns I need: 
1. Platform ID (in this case it will always be Tiktok)
2. Person ID (in this case it will be A)
3. Date of the video watched (OKAY WE'RE HALF WAY THERE)
4. What day of the week correlates with that date 
5. Time of the video watched (for 0 it would be 12:33:12)
6. Time of each video watched

In [173]:
tablett2.insert(0, "Platform", ["Tiktok"], True)
print(tablett2)

ValueError: Length of values (1) does not match length of index (78194)

Okay, troubleshooting here. Have to make "Tiktok" appear 78194 times!!!!

In [ ]:
tablett2.assign(Platform="Tiktok")

,Date,Link,Platform
0,2026-03-20 12:33:12,https://www.tiktokv.com/share/video/7616782825...,Tiktok
1,2026-03-20 12:32:59,https://www.tiktokv.com/share/video/7618946244...,Tiktok
2,2026-03-20 12:02:37,https://www.tiktokv.com/share/video/7619059457...,Tiktok
3,2026-03-20 12:02:36,https://www.tiktokv.com/share/video/7501170729...,Tiktok
4,2026-03-20 11:53:03,https://www.tiktokv.com/share/video/7618388640...,Tiktok
...,...,...,...
78189,2025-09-22 00:40:31,https://www.tiktokv.com/share/video/7540322581...,Tiktok
78190,2025-09-22 00:39:59,https://www.tiktokv.com/share/video/7550818580...,Tiktok
78191,2025-09-22 00:39:53,https://www.tiktokv.com/share/video/7552242622...,Tiktok
78192,2025-09-22 00:39:44,https://www.tiktokv.com/share/video/7552286495...,Tiktok
78193,2025-09-22 00:39:42,https://www.tiktokv.com/share/video/7541185128...,Tiktok

GOD BLESS THE INTERNET! Here's where it gave me the code to do that https://stackoverflow.com/questions/44657226/how-to-insert-a-new-column-with-repeated-values-into-a-pandas-table omg so much easier

In [ ]:
tablett2.assign(Platform='Tiktok')[['Platform'] + tablett2.columns.tolist()]

,Platform,Date,Link
0,Tiktok,2026-03-20 12:33:12,https://www.tiktokv.com/share/video/7616782825...
1,Tiktok,2026-03-20 12:32:59,https://www.tiktokv.com/share/video/7618946244...
2,Tiktok,2026-03-20 12:02:37,https://www.tiktokv.com/share/video/7619059457...
3,Tiktok,2026-03-20 12:02:36,https://www.tiktokv.com/share/video/7501170729...
4,Tiktok,2026-03-20 11:53:03,https://www.tiktokv.com/share/video/7618388640...
...,...,...,...
78189,Tiktok,2025-09-22 00:40:31,https://www.tiktokv.com/share/video/7540322581...
78190,Tiktok,2025-09-22 00:39:59,https://www.tiktokv.com/share/video/7550818580...
78191,Tiktok,2025-09-22 00:39:53,https://www.tiktokv.com/share/video/7552242622...
78192,Tiktok,2025-09-22 00:39:44,https://www.tiktokv.com/share/video/7552286495...
78193,Tiktok,2025-09-22 00:39:42,https://www.tiktokv.com/share/video/7541185128...

In [ ]:
tablett2.assign(Platform="Tiktok", Person="A")[['Platform', 'Person'] + tablett2.columns.tolist()]

,Platform,Person,Date,Link
0,Tiktok,A,2026-03-20 12:33:12,https://www.tiktokv.com/share/video/7616782825...
1,Tiktok,A,2026-03-20 12:32:59,https://www.tiktokv.com/share/video/7618946244...
2,Tiktok,A,2026-03-20 12:02:37,https://www.tiktokv.com/share/video/7619059457...
3,Tiktok,A,2026-03-20 12:02:36,https://www.tiktokv.com/share/video/7501170729...
4,Tiktok,A,2026-03-20 11:53:03,https://www.tiktokv.com/share/video/7618388640...
...,...,...,...,...
78189,Tiktok,A,2025-09-22 00:40:31,https://www.tiktokv.com/share/video/7540322581...
78190,Tiktok,A,2025-09-22 00:39:59,https://www.tiktokv.com/share/video/7550818580...
78191,Tiktok,A,2025-09-22 00:39:53,https://www.tiktokv.com/share/video/7552242622...
78192,Tiktok,A,2025-09-22 00:39:44,https://www.tiktokv.com/share/video/7552286495...
78193,Tiktok,A,2025-09-22 00:39:42,https://www.tiktokv.com/share/video/7541185128...

Full disclosure, I tried a bunch of different iterations for the above. I had the above pieces but the wrong syntax so Claude helped bc I had () where I should have had commas.

In [ ]:
Tempsave= tablett2.assign(Platform="Tiktok", Person="A")[['Platform', 'Person'] + tablett2.columns.tolist()]

...So I know if I keep making data frames this thing will be a PAIN to replicate for multiple platforms for multiple people, BUT while i'm still messing around this is my temp plan. So hopefully once I finish it I can streamline it into a process that actually can be more replicatable

Now I need to break up the date from the time

In [ ]:
type(Tempsave["Date"].iloc[0])

str

In [ ]:
Tempsave["datetime"] = pd.to_datetime(Tempsave["Date"])
Tempsave.head()

,Platform,Person,Date,Link,datetime
0,Tiktok,A,2026-03-20 12:33:12,https://www.tiktokv.com/share/video/7616782825...,2026-03-20 12:33:12
1,Tiktok,A,2026-03-20 12:32:59,https://www.tiktokv.com/share/video/7618946244...,2026-03-20 12:32:59
2,Tiktok,A,2026-03-20 12:02:37,https://www.tiktokv.com/share/video/7619059457...,2026-03-20 12:02:37
3,Tiktok,A,2026-03-20 12:02:36,https://www.tiktokv.com/share/video/7501170729...,2026-03-20 12:02:36
4,Tiktok,A,2026-03-20 11:53:03,https://www.tiktokv.com/share/video/7618388640...,2026-03-20 11:53:03

Great, converted my string to date time but it got added to the end. I'm going to reorder the columns when everything is done bc that's cosmetic at this point.

In [ ]:
Tempsave["date"]=Tempsave["datetime"].dt.date
Tempsave.head()

,Platform,Person,Date,Link,datetime,date
0,Tiktok,A,2026-03-20 12:33:12,https://www.tiktokv.com/share/video/7616782825...,2026-03-20 12:33:12,2026-03-20
1,Tiktok,A,2026-03-20 12:32:59,https://www.tiktokv.com/share/video/7618946244...,2026-03-20 12:32:59,2026-03-20
2,Tiktok,A,2026-03-20 12:02:37,https://www.tiktokv.com/share/video/7619059457...,2026-03-20 12:02:37,2026-03-20
3,Tiktok,A,2026-03-20 12:02:36,https://www.tiktokv.com/share/video/7501170729...,2026-03-20 12:02:36,2026-03-20
4,Tiktok,A,2026-03-20 11:53:03,https://www.tiktokv.com/share/video/7618388640...,2026-03-20 11:53:03,2026-03-20

Okay... now I have two columns called date... The old one called "Date" which is a string, and the new one called "date"which is in date time. This will be annoying but maybe after I'm done I can figure out how to clean that one up lol. Maybe I can rename "Date" to like "string" or something earlier on??? Since I need date time format for graphing?

In [ ]:
Tempsave["Time"]=Tempsave["datetime"].dt.time
Tempsave

,Platform,Person,Date,Link,datetime,date,Time
0,Tiktok,A,2026-03-20 12:33:12,https://www.tiktokv.com/share/video/7616782825...,2026-03-20 12:33:12,2026-03-20,12:33:12
1,Tiktok,A,2026-03-20 12:32:59,https://www.tiktokv.com/share/video/7618946244...,2026-03-20 12:32:59,2026-03-20,12:32:59
2,Tiktok,A,2026-03-20 12:02:37,https://www.tiktokv.com/share/video/7619059457...,2026-03-20 12:02:37,2026-03-20,12:02:37
3,Tiktok,A,2026-03-20 12:02:36,https://www.tiktokv.com/share/video/7501170729...,2026-03-20 12:02:36,2026-03-20,12:02:36
4,Tiktok,A,2026-03-20 11:53:03,https://www.tiktokv.com/share/video/7618388640...,2026-03-20 11:53:03,2026-03-20,11:53:03
...,...,...,...,...,...,...,...
78189,Tiktok,A,2025-09-22 00:40:31,https://www.tiktokv.com/share/video/7540322581...,2025-09-22 00:40:31,2025-09-22,00:40:31
78190,Tiktok,A,2025-09-22 00:39:59,https://www.tiktokv.com/share/video/7550818580...,2025-09-22 00:39:59,2025-09-22,00:39:59
78191,Tiktok,A,2025-09-22 00:39:53,https://www.tiktokv.com/share/video/7552242622...,2025-09-22 00:39:53,2025-09-22,00:39:53
78192,Tiktok,A,2025-09-22 00:39:44,https://www.tiktokv.com/share/video/7552286495...,2025-09-22 00:39:44,2025-09-22,00:39:44
78193,Tiktok,A,2025-09-22 00:39:42,https://www.tiktokv.com/share/video/7541185128...,2025-09-22 00:39:42,2025-09-22,00:39:42

Now to turn "date" with the lowercase D into a day

In [ ]:
Tempsave["Day"]=Tempsave["datetime"].dt.day
Tempsave.head()

,Platform,Person,Date,Link,datetime,date,Time,Day
0,Tiktok,A,2026-03-20 12:33:12,https://www.tiktokv.com/share/video/7616782825...,2026-03-20 12:33:12,2026-03-20,12:33:12,20
1,Tiktok,A,2026-03-20 12:32:59,https://www.tiktokv.com/share/video/7618946244...,2026-03-20 12:32:59,2026-03-20,12:32:59,20
2,Tiktok,A,2026-03-20 12:02:37,https://www.tiktokv.com/share/video/7619059457...,2026-03-20 12:02:37,2026-03-20,12:02:37,20
3,Tiktok,A,2026-03-20 12:02:36,https://www.tiktokv.com/share/video/7501170729...,2026-03-20 12:02:36,2026-03-20,12:02:36,20
4,Tiktok,A,2026-03-20 11:53:03,https://www.tiktokv.com/share/video/7618388640...,2026-03-20 11:53:03,2026-03-20,11:53:03,20

Well just changing it to day was worth a shot lol

In [ ]:
Tempsave["Day"]=Tempsave["datetime"].dt.day_name
Tempsave.head()

,Platform,Person,Date,Link,datetime,date,Time,Day
0,Tiktok,A,2026-03-20 12:33:12,https://www.tiktokv.com/share/video/7616782825...,2026-03-20 12:33:12,2026-03-20,12:33:12,<bound method PandasDelegate._add_delegate_acc...
1,Tiktok,A,2026-03-20 12:32:59,https://www.tiktokv.com/share/video/7618946244...,2026-03-20 12:32:59,2026-03-20,12:32:59,<bound method PandasDelegate._add_delegate_acc...
2,Tiktok,A,2026-03-20 12:02:37,https://www.tiktokv.com/share/video/7619059457...,2026-03-20 12:02:37,2026-03-20,12:02:37,<bound method PandasDelegate._add_delegate_acc...
3,Tiktok,A,2026-03-20 12:02:36,https://www.tiktokv.com/share/video/7501170729...,2026-03-20 12:02:36,2026-03-20,12:02:36,<bound method PandasDelegate._add_delegate_acc...
4,Tiktok,A,2026-03-20 11:53:03,https://www.tiktokv.com/share/video/7618388640...,2026-03-20 11:53:03,2026-03-20,11:53:03,<bound method PandasDelegate._add_delegate_acc...

In [ ]:
Tempsave["Day"].iloc[0]

In [ ]:
Tempsave["Day"]=Tempsave["datetime"].dt.day_name()
Tempsave.head()

,Platform,Person,Date,Link,datetime,date,Time,Day
0,Tiktok,A,2026-03-20 12:33:12,https://www.tiktokv.com/share/video/7616782825...,2026-03-20 12:33:12,2026-03-20,12:33:12,Friday
1,Tiktok,A,2026-03-20 12:32:59,https://www.tiktokv.com/share/video/7618946244...,2026-03-20 12:32:59,2026-03-20,12:32:59,Friday
2,Tiktok,A,2026-03-20 12:02:37,https://www.tiktokv.com/share/video/7619059457...,2026-03-20 12:02:37,2026-03-20,12:02:37,Friday
3,Tiktok,A,2026-03-20 12:02:36,https://www.tiktokv.com/share/video/7501170729...,2026-03-20 12:02:36,2026-03-20,12:02:36,Friday
4,Tiktok,A,2026-03-20 11:53:03,https://www.tiktokv.com/share/video/7618388640...,2026-03-20 11:53:03,2026-03-20,11:53:03,Friday

Oh pandas... the () make all the difference. (had to google that one)
Well... just glad it worked. Now I need to do the delta for time.... and hopefully that's easy

In [ ]:
Tempsave["Watch Time"] = pd.to_timedelta(Tempsave["Time"])

TypeError: Invalid type for timedelta scalar: <class 'datetime.time'>

OH MY GOD YOU CAN'T DETLA TIME A TIMECODE?????? IT HAS TO BE A STRING????? I CONVERTED IT TO DATE TIME FROM A STRING. WE'VE BEEN TO THE MOON AND WE CAN'T DO THAT?
![Image](https://merriam-webster.com/assets/mw/images/article/art-wap-article-main/headdesk-2560-44956df35ded58048d9aa3923774657c@2x.jpg)

In [ ]:
Tempsave["Watch Time"] = Tempsave["datetime"].diff().abs()
Tempsave.head()

,Platform,Person,Date,Link,datetime,date,Time,Day,Watch Time
0,Tiktok,A,2026-03-20 12:33:12,https://www.tiktokv.com/share/video/7616782825...,2026-03-20 12:33:12,2026-03-20,12:33:12,Friday,NaT
1,Tiktok,A,2026-03-20 12:32:59,https://www.tiktokv.com/share/video/7618946244...,2026-03-20 12:32:59,2026-03-20,12:32:59,Friday,0 days 00:00:13
2,Tiktok,A,2026-03-20 12:02:37,https://www.tiktokv.com/share/video/7619059457...,2026-03-20 12:02:37,2026-03-20,12:02:37,Friday,0 days 00:30:22
3,Tiktok,A,2026-03-20 12:02:36,https://www.tiktokv.com/share/video/7501170729...,2026-03-20 12:02:36,2026-03-20,12:02:36,Friday,0 days 00:00:01
4,Tiktok,A,2026-03-20 11:53:03,https://www.tiktokv.com/share/video/7618388640...,2026-03-20 11:53:03,2026-03-20,11:53:03,Friday,0 days 00:09:33

Full disclosure, I got so confused with the detla... I went to Claude and was like "please help" and it gave me the .diff().abs()

So... we've done most of what I set out to do now time to clean it up

In [ ]:
ttdf2a = Tempsave[["Platform", "Person", "date", "Day", "Time", "Watch Time"]]
ttdf2a.head()

  Platform Person        date     Day      Time      Watch Time
0   Tiktok      A  2026-03-20  Friday  12:33:12             NaT
1   Tiktok      A  2026-03-20  Friday  12:32:59 0 days 00:00:13
2   Tiktok      A  2026-03-20  Friday  12:02:37 0 days 00:30:22
3   Tiktok      A  2026-03-20  Friday  12:02:36 0 days 00:00:01
4   Tiktok      A  2026-03-20  Friday  11:53:03 0 days 00:09:33

![Image](https://i.imgflip.com/6p8gkl.jpg)

## Okay... So, I think what I need to do to streamline it: 
1. data frame out of the "['Watch History'].iloc[15]" within the OG file tiktok gives me 
2. (Potentially change the name of Date to something so I can use Date later but not confuse myself or the system)
3. Add a column for Date (in the case of what i did "date") with the date in day time 
4. Add a column for day
5. Add a column for time but DON'T convert it to date time 
6. Calcuate watch time not with the time detla 
7. Add a column for Platform
8. Add a column for Person
9. Save that final as a data frame. 

I'm hoping that will eliminate the problems I had and how many data frames I had to save to get to a final. 

Still haven't come up with a naming convention so that's going to be done for the next milestone as I bring in other people's data. I'm beta testing on my own right now.

#### Next Steps
1. Finish collecting data by Thursday 
2. Start making all the Tiktok Watch Time Tables to have by Milestone 2 
3. If I'm feeling really bold start figuring out how to combine them all. 
4. Webscraping at some point by the other three tables need them.... FUN 
5. Start graphing!

### Milestone 2 Starts here!

Wow, it hasn't even been a week since Milestone two and oh boy I'm finding MORE things to do. HUZZAH! 
First, found out that on the Instagram app you can download files as .json, where as on the desktop you can't. If I ever meet Mark Zuckerberg I will ask him one question only, "what is wrong with you?" 
ANYWAYS, so I was able to get 3/4 tables done... or so I thought. Are the two tables that show watch time done? NOPE. I need to account for log-in time. I... misunderstood Tiktok's column for log-in history.... I thought it meant every time you type your username and password, *not* every time you open the app. So, shout out Dr. Silva for telling me that data was in there so I have to give another look. 

So... I'm still doing my little beta test on how to finalize these tables before I move on to working with other people's data. I figure if I'm the one digging through my own data I'm okay if it gets messy. I know everything that's in there, and I'm actually pretty boring online. It's all pottery videos, real housewives of salt lake city, and a too high screentime. So I'm okay having other people look at this, lol.

In [ ]:
with open("Julia Beta recommended_topics.json") as j:
    IGrecommendedtopics = json.load(j)

In [ ]:
with open("Julia Beta videos_watched.json") as j:
    IGactivity = json.load(j)

In [ ]:
### IGrecommendedtopics

{'topics_your_topics': [{'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Crafts',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Pottery & Ceramics',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Musical Performances',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Foods',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'TV & Movies Celebrities',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Video Games',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Fashion Products',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'East Asian Food',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Alcoholic Beverages',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Baked Goods',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Ground Transportation',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Gym Workouts',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Body Modification',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Fashion',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Non-Alcoholic Beverages',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Regional Cuisines',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Drinks',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Personal Celebrations',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Cakes',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Beauty',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Pastries',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Visual Arts',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Vegetables',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Food Trends',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Animation TV & Movies',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Produce',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Coffee Drinks',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Dog Breeds',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Food Trends by Diet',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Types of Sports',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Dance',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Cookies',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Travel Destinations',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'TV & Movies by Genre',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Mammals',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Birthdays',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '', 'value': 'Dogs', 'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Veganism',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Jewelry',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Cars & Trucks',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Asian Food',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Food History & Culture',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Animals',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Hair Care',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Body Art',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Farm Animals',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '', 'value': 'Cats', 'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Fruits',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Recipes',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Clothing & Accessories',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Desserts',
     'timestamp': 0}}},
  {'title': '',
   'media_map_data': {},
   'string_map_data': {'Name': {'href': '',
     'value': 'Pets',
     'timestamp': 0}}}]}

In [ ]:
type(IGrecommendedtopics)

dict

In [ ]:
IGrecommendedtopics.keys()

dict_keys(['topics_your_topics'])

In [ ]:
topics = [item['string_map_data']['Name']['value'] for item in IGrecommendedtopics['topics_your_topics']]

In [ ]:
IG1A = pd.DataFrame(topics, columns=["Topic"])
IG1A

                      Topic
0                    Crafts
1        Pottery & Ceramics
2      Musical Performances
3                     Foods
4   TV & Movies Celebrities
5               Video Games
6          Fashion Products
7           East Asian Food
8       Alcoholic Beverages
9               Baked Goods
10    Ground Transportation
11             Gym Workouts
12        Body Modification
13                  Fashion
14  Non-Alcoholic Beverages
15        Regional Cuisines
16                   Drinks
17    Personal Celebrations
18                    Cakes
19                   Beauty
20                 Pastries
21              Visual Arts
22               Vegetables
23              Food Trends
24    Animation TV & Movies
25                  Produce
26            Coffee Drinks
27               Dog Breeds
28      Food Trends by Diet
29          Types of Sports
30                    Dance
31                  Cookies
32      Travel Destinations
33     TV & Movies by Genre
34                  Mammals
35                Birthdays
36                     Dogs
37                 Veganism
38                  Jewelry
39            Cars & Trucks
40               Asian Food
41   Food History & Culture
42                  Animals
43                Hair Care
44                 Body Art
45             Farm Animals
46                     Cats
47                   Fruits
48                  Recipes
49   Clothing & Accessories
50                 Desserts
51                     Pets

In [ ]:
IG1A_final = IG1A.assign(Platform="Instagram", Person="A")[["Platform", "Person"] + IG1A.columns.tolist()]
IG1A_final.head()

    Platform Person                    Topic
0  Instagram      A                   Crafts
1  Instagram      A       Pottery & Ceramics
2  Instagram      A     Musical Performances
3  Instagram      A                    Foods
4  Instagram      A  TV & Movies Celebrities

In [ ]:
IGactivity

[{'timestamp': 1774902960,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWhQVSSAd7P/',
    'href': 'https://www.instagram.com/reel/DWhQVSSAd7P/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://stan.store/tarakermiet'},
       {'label': 'Name', 'value': 'Tara Kermiet | Burnout + Career Coach'},
       {'label': 'Username', 'value': 'tarakermiet'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18107755963665605:1774902960::DYIImpressionsData'},
 {'timestamp': 1774905887,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWhKrFzCUEV/',
    'href': 'https://www.instagram.com/reel/DWhKrFzCUEV/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': 'https://www.pi.fyi/welcome'},
       {'label': 'Name',
        'value': 'â\xad\x90ï¸\x8f Perfectly Imperfect â\xad\x90ï¸\x8f'},
       {'label': 'Username', 'value': 'perfectlyimperfect'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18310119415256128:1774905887::DYIImpressionsData'},
 {'timestamp': 1774908114,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWhOdRqDcCT/',
    'href': 'https://www.instagram.com/reel/DWhOdRqDcCT/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/awalmartparkinglot'},
       {'label': 'Name',
        'value': 'Miss Redacted ð\x9f\x92\x85ð\x9f\x8f»ð\x9fª©ð\x9f¤\xa0'},
       {'label': 'Username', 'value': 'awalmartparkinglott'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18578712475019167:1774908114::DYIImpressionsData'},
 {'timestamp': 1774911917,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWhWc1Iig1y/',
    'href': 'https://www.instagram.com/reel/DWhWc1Iig1y/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': 'http://likeshop.me/bravotv'},
       {'label': 'Name', 'value': 'Bravo'},
       {'label': 'Username', 'value': 'bravotv'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18062489216380208:1774911917::DYIImpressionsData'},
 {'timestamp': 1774912335,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWcSalEic8L/',
    'href': 'https://www.instagram.com/reel/DWcSalEic8L/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': ''},
       {'label': 'Username', 'value': 'gentlesimmer'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17952887547103349:1774912335::DYIImpressionsData'},
 {'timestamp': 1774315150,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWfVV2ggKVT/',
    'href': 'https://www.instagram.com/reel/DWfVV2ggKVT/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'Christinaâ\x80¢ Luxury World Traveler'},
       {'label': 'Username', 'value': 'christinaswanderlust'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18072078473647563:1774315150::DYIImpressionsData'},
 {'timestamp': 1774385100,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWY78qOi8KI/',
    'href': 'https://www.instagram.com/reel/DWY78qOi8KI/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name',
        'value': 'â\x98\x81ï¸\x8f Guan-guan | ç½\x90ç½\x90 ð\x9f\x90¾'},
       {'label': 'Username', 'value': 'guanguan_official'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17867528694504325:1774385100::DYIImpressionsData'},
 {'timestamp': 1774919931,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWhkqxDJKlr/',
    'href': 'https://www.instagram.com/reel/DWhkqxDJKlr/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://bravointimates.com/newsletter-sign-up/?fbclid=IwAR3gOZmiy_w74c-2kDuOoVl4ivUCF_mR8aGo-c53chfgDerCwjkrLj4u4Hg'},
       {'label': 'Name', 'value': 'Bra~vo Intimates'},
       {'label': 'Username', 'value': 'bravo_intimates'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18092714419888744:1774919931::DYIImpressionsData'},
 {'timestamp': 1774919938,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWgrRwcDD2s/',
    'href': 'https://www.instagram.com/p/DWgrRwcDD2s/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/lovebravissimo'},
       {'label': 'Name', 'value': 'Bravissimo'},
       {'label': 'Username', 'value': 'lovebravissimo'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18207720214333644:1774919938::DYIImpressionsData'},
 {'timestamp': 1774919991,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWhMhMZkXvc/',
    'href': 'https://www.instagram.com/reel/DWhMhMZkXvc/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/thepeachbellini'},
       {'label': 'Name',
        'value': 'ð\x9d\x93\x9fð\x9d\x93®ð\x9d\x93ªð\x9d\x93¬ð\x9d\x93± ð\x9d\x93\x91ð\x9d\x93®ð\x9d\x93µð\x9d\x93µð\x9d\x93²ð\x9d\x93·ð\x9d\x93² ð\x9f\x8d\x91'},
       {'label': 'Username', 'value': 'thepeachbellini'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18117224131730238:1774919991::DYIImpressionsData'},
 {'timestamp': 1774920013,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWHfaNrAAmv/',
    'href': 'https://www.instagram.com/reel/DWHfaNrAAmv/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://almabloomstudio.etsy.com/listing/4386909248'},
       {'label': 'Name', 'value': 'Catha | life abroad in Sweden'},
       {'label': 'Username', 'value': 'catharina.barbosa'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18076249556123935:1774920013::DYIImpressionsData'},
 {'timestamp': 1774920013,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWfhUs_DXlh/',
    'href': 'https://www.instagram.com/reel/DWfhUs_DXlh/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/Axaila?utm_source=linktree_profile_share&ltsid=cd731771-51a0-4f50-a8ab-5356087e6475'},
       {'label': 'Name', 'value': 'Azaila ð\x9f\x8d\x93ð\x9fª½'},
       {'label': 'Username', 'value': 'axaila'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18205531456327247:1774920013::DYIImpressionsData'},
 {'timestamp': 1774920013,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWhAiYViVOb/',
    'href': 'https://www.instagram.com/reel/DWhAiYViVOb/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'Chris Cruise'},
       {'label': 'Username', 'value': 'djchriscruise'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18081791876073760:1774920013::DYIImpressionsData'},
 {'timestamp': 1774920459,
  'media': [],
  'label_values': [{'label': 'Ad library public URL',
    'value': 'https://www.facebook.com/ads/library/?id=723784607393130',
    'href': 'https://www.facebook.com/ads/library/?id=723784607393130'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWVmwB9DCDY/',
    'href': 'https://www.instagram.com/p/DWVmwB9DCDY/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://blackmilkclothing.com/collections/the-elder-scrolls?utm_source=facebook&utm_medium=social&utm_campaign=TheElderScrolls_Signup&utm_content=TES'},
       {'label': 'Name', 'value': 'BlackMilk Clothing'},
       {'label': 'Username', 'value': 'blackmilkclothing'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18094280849115205:1774920459::DYIImpressionsData'},
 {'timestamp': 1774925240,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWh5L57DDg9/',
    'href': 'https://www.instagram.com/reel/DWh5L57DDg9/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/meghantonjes'},
       {'label': 'Name', 'value': 'meghan tonjes'},
       {'label': 'Username', 'value': 'meghantonjes'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17922790221279266:1774925240::DYIImpressionsData'},
 {'timestamp': 1774925272,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWh9qLGifpT/',
    'href': 'https://www.instagram.com/reel/DWh9qLGifpT/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': 'https://bio.to/ginwigmore'},
       {'label': 'Name', 'value': 'Gin Wigmore'},
       {'label': 'Username', 'value': 'ginwigmore'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18075848489169323:1774925272::DYIImpressionsData'},
 {'timestamp': 1774925429,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWhgHXgDFVe/',
    'href': 'https://www.instagram.com/reel/DWhgHXgDFVe/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': 'https://newsin.bio/ny1'},
       {'label': 'Name', 'value': 'Spectrum News NY1'},
       {'label': 'Username', 'value': 'ny1'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18107112806506369:1774925429::DYIImpressionsData'},
 {'timestamp': 1774956532,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWiUM21ApZu/',
    'href': 'https://www.instagram.com/reel/DWiUM21ApZu/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'http://www.eurovision.com/app'},
       {'label': 'Name', 'value': 'Eurovision Song Contest'},
       {'label': 'Username', 'value': 'eurovision'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18111142369690476:1774956532::DYIImpressionsData'},
 {'timestamp': 1774956549,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWaN6C5gMv9/',
    'href': 'https://www.instagram.com/p/DWaN6C5gMv9/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/Trashie.io'},
       {'label': 'Name', 'value': 'Trashie'},
       {'label': 'Username', 'value': 'trashie'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18059435369695670:1774956549::DYIImpressionsData'},
 {'timestamp': 1774956620,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWTrFCYk839/',
    'href': 'https://www.instagram.com/reel/DWTrFCYk839/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'Potato.'},
       {'label': 'Username', 'value': 'theiconicpotato_'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18071465762556217:1774956620::DYIImpressionsData'},
 {'timestamp': 1774956630,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWhCEFdAedb/',
    'href': 'https://www.instagram.com/reel/DWhCEFdAedb/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': 'http://linkin.bio/youtube/'},
       {'label': 'Name', 'value': 'YouTube'},
       {'label': 'Username', 'value': 'youtube'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18086089742462546:1774956630::DYIImpressionsData'},
 {'timestamp': 1774956630,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWhs2-5jSvp/',
    'href': 'https://www.instagram.com/reel/DWhs2-5jSvp/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/davisburleson'},
       {'label': 'Name', 'value': 'Davis Burleson'},
       {'label': 'Username', 'value': 'davisburleson'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17866723602605206:1774956630::DYIImpressionsData'},
 {'timestamp': 1774956630,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWh_8zckb7G/',
    'href': 'https://www.instagram.com/reel/DWh_8zckb7G/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/colbertlateshow'},
       {'label': 'Name', 'value': 'The Late Show'},
       {'label': 'Username', 'value': 'colbertlateshow'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17889814071446516:1774956630::DYIImpressionsData'},
 {'timestamp': 1774956657,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DVmMFgHkrzN/',
    'href': 'https://www.instagram.com/reel/DVmMFgHkrzN/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'Seiler (Syler)'},
       {'label': 'Username', 'value': 'mango.minded'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18098330344756643:1774956657::DYIImpressionsData'},
 {'timestamp': 1774956679,
  'media': [],
  'label_values': [{'label': 'Ad library public URL',
    'value': 'https://www.facebook.com/ads/library/?id=727437660358923',
    'href': 'https://www.facebook.com/ads/library/?id=727437660358923'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWhPE9jDBw9/',
    'href': 'https://www.instagram.com/p/DWhPE9jDBw9/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://visitstore.bio/behrpaint'},
       {'label': 'Name', 'value': 'BEHRÂ® Paint'},
       {'label': 'Username', 'value': 'behrpaint'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18063391145691928:1774956679::DYIImpressionsData'},
 {'timestamp': 1774956697,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWUZbn-DEbz/',
    'href': 'https://www.instagram.com/reel/DWUZbn-DEbz/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'hannah preston, mph'},
       {'label': 'Username', 'value': 'healthpolicyprincess'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17867312271502965:1774956697::DYIImpressionsData'},
 {'timestamp': 1774956697,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWho5j7j0fP/',
    'href': 'https://www.instagram.com/reel/DWho5j7j0fP/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://shopmy.us/whitneyleavitt'},
       {'label': 'Name', 'value': 'Whitney Leavitt'},
       {'label': 'Username', 'value': 'whitleavitt'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17873251410577073:1774956697::DYIImpressionsData'},
 {'timestamp': 1774956698,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWH5PNpAfZ4/',
    'href': 'https://www.instagram.com/reel/DWH5PNpAfZ4/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://beacons.ai/cocoshihtzu'},
       {'label': 'Name', 'value': 'Cocoð\x9f\x90¶'},
       {'label': 'Username', 'value': 'coco.the.tzuu'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17952136467113699:1774956698::DYIImpressionsData'},
 {'timestamp': 1774956717,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWhi3tiTv8j/',
    'href': 'https://www.instagram.com/reel/DWhi3tiTv8j/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://www.melaniebracewell.com/aus-nz'},
       {'label': 'Name', 'value': 'Melanie Bracewell'},
       {'label': 'Username', 'value': 'melaniebracewell'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18060211001414139:1774956717::DYIImpressionsData'},
 {'timestamp': 1774977810,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWjPaDeANSt/',
    'href': 'https://www.instagram.com/reel/DWjPaDeANSt/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'http://www.dwhighamceramics.com'},
       {'label': 'Name', 'value': 'D Whigham Ceramics'},
       {'label': 'Username', 'value': 'dwhighamceramics'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17914316430344601:1774977810::DYIImpressionsData'},
 {'timestamp': 1774979290,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWjcsEKjqn4/',
    'href': 'https://www.instagram.com/reel/DWjcsEKjqn4/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://creatorlink.shop/4uya8Cq'},
       {'label': 'Name', 'value': 'Carleigh Bodrug'},
       {'label': 'Username', 'value': 'plantyou'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18043161626761594:1774979290::DYIImpressionsData'},
 {'timestamp': 1774986372,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWj4YBoDyeq/',
    'href': 'https://www.instagram.com/reel/DWj4YBoDyeq/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'Josephine Datz'},
       {'label': 'Username', 'value': 'datzliving'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18068954834299904:1774986372::DYIImpressionsData'},
 {'timestamp': 1774989677,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWjuCrkkdyI/',
    'href': 'https://www.instagram.com/reel/DWjuCrkkdyI/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': 'https://atmilb.com/49sx0J2'},
       {'label': 'Name', 'value': 'Akron RubberDucks'},
       {'label': 'Username', 'value': 'akronrubberducks'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18004987154889422:1774989677::DYIImpressionsData'},
 {'timestamp': 1774989748,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWh7ITrjHBI/',
    'href': 'https://www.instagram.com/reel/DWh7ITrjHBI/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://app.tern.travel/public/forms/8yRHYCP4yWsR6d-L6n0CuQ/responses/xHt-zdQHJP9bLd78flBxiQ/edit'},
       {'label': 'Name', 'value': 'Shana Matos'},
       {'label': 'Username', 'value': 'theglutenfreetravelagent_'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18048133391729959:1774989748::DYIImpressionsData'},
 {'timestamp': 1774989752,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/reel/DWdy2V7AJ86/',

In [ ]:
IG2A= pd.DataFrame(IGactivity)

In [ ]:
IG2A.head()

,timestamp,media,label_values,fbid
0,1774902960,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18107755963665605:1774902960...
1,1774905887,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18310119415256128:1774905887...
2,1774908114,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18578712475019167:1774908114...
3,1774911917,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18062489216380208:1774911917...
4,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17952887547103349:1774912335...

In [ ]:
IG2A.tail()

,timestamp,media,label_values,fbid
1590,1775043092,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18104102995904540:1775043092...
1591,1775268603,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18078362138529592:1775268603...
1592,1775313945,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18091168172146640:1775313945...
1593,1775315270,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17996132753759009:1775315270...
1594,1775347188,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18401097919195000:1775347188...

In [ ]:
type(IG2A["timestamp"])

pandas.core.series.Series

Okay so I need to pull out the time stamp as date time to do everything. I think it's miliseconds.... joy.

In [ ]:
IG2A["timestamp"]=IG2A["timestamp"].dt.microseconds

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
IG2A['date'] = pd.to_datetime(IG2A['timestamp'], unit='ms')

In [ ]:
IG2A

,timestamp,media,label_values,fbid,date
0,1774902960,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18107755963665605:1774902960...,1970-01-21 13:01:42.960
1,1774905887,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18310119415256128:1774905887...,1970-01-21 13:01:45.887
2,1774908114,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18578712475019167:1774908114...,1970-01-21 13:01:48.114
3,1774911917,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18062489216380208:1774911917...,1970-01-21 13:01:51.917
4,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17952887547103349:1774912335...,1970-01-21 13:01:52.335
...,...,...,...,...,...
1590,1775043092,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18104102995904540:1775043092...,1970-01-21 13:04:03.092
1591,1775268603,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18078362138529592:1775268603...,1970-01-21 13:07:48.603
1592,1775313945,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18091168172146640:1775313945...,1970-01-21 13:08:33.945
1593,1775315270,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17996132753759009:1775315270...,1970-01-21 13:08:35.270
1594,1775347188,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18401097919195000:1775347188...,1970-01-21 13:09:07.188

...okay not milliseconds.

In [ ]:
IG2A['date'] = pd.to_datetime(IG2A['timestamp'], unit='us')

In [ ]:
IG2A

,timestamp,media,label_values,fbid,date
0,1774902960,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18107755963665605:1774902960...,1970-01-01 00:29:34.902960
1,1774905887,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18310119415256128:1774905887...,1970-01-01 00:29:34.905887
2,1774908114,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18578712475019167:1774908114...,1970-01-01 00:29:34.908114
3,1774911917,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18062489216380208:1774911917...,1970-01-01 00:29:34.911917
4,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17952887547103349:1774912335...,1970-01-01 00:29:34.912335
...,...,...,...,...,...
1590,1775043092,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18104102995904540:1775043092...,1970-01-01 00:29:35.043092
1591,1775268603,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18078362138529592:1775268603...,1970-01-01 00:29:35.268603
1592,1775313945,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18091168172146640:1775313945...,1970-01-01 00:29:35.313945
1593,1775315270,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17996132753759009:1775315270...,1970-01-01 00:29:35.315270
1594,1775347188,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18401097919195000:1775347188...,1970-01-01 00:29:35.347188

Not... microsecond?

In [ ]:
IG2A['date'] = pd.to_datetime(IG2A['timestamp'], unit='ns')
IG2A

,timestamp,media,label_values,fbid,date
0,1774902960,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18107755963665605:1774902960...,1970-01-01 00:00:01.774902960
1,1774905887,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18310119415256128:1774905887...,1970-01-01 00:00:01.774905887
2,1774908114,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18578712475019167:1774908114...,1970-01-01 00:00:01.774908114
3,1774911917,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18062489216380208:1774911917...,1970-01-01 00:00:01.774911917
4,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17952887547103349:1774912335...,1970-01-01 00:00:01.774912335
...,...,...,...,...,...
1590,1775043092,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18104102995904540:1775043092...,1970-01-01 00:00:01.775043092
1591,1775268603,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18078362138529592:1775268603...,1970-01-01 00:00:01.775268603
1592,1775313945,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18091168172146640:1775313945...,1970-01-01 00:00:01.775313945
1593,1775315270,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17996132753759009:1775315270...,1970-01-01 00:00:01.775315270
1594,1775347188,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18401097919195000:1775347188...,1970-01-01 00:00:01.775347188

So... not Nano seconds

In [ ]:
IG2A['datetime'] = pd.to_datetime(IG2A['timestamp'], unit='s')
IG2A

,timestamp,media,label_values,fbid,date,datetime
0,1774902960,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18107755963665605:1774902960...,1970-01-01 00:00:01.774902960,2026-03-30 20:36:00
1,1774905887,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18310119415256128:1774905887...,1970-01-01 00:00:01.774905887,2026-03-30 21:24:47
2,1774908114,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18578712475019167:1774908114...,1970-01-01 00:00:01.774908114,2026-03-30 22:01:54
3,1774911917,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18062489216380208:1774911917...,1970-01-01 00:00:01.774911917,2026-03-30 23:05:17
4,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17952887547103349:1774912335...,1970-01-01 00:00:01.774912335,2026-03-30 23:12:15
...,...,...,...,...,...,...
1590,1775043092,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18104102995904540:1775043092...,1970-01-01 00:00:01.775043092,2026-04-01 11:31:32
1591,1775268603,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18078362138529592:1775268603...,1970-01-01 00:00:01.775268603,2026-04-04 02:10:03
1592,1775313945,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18091168172146640:1775313945...,1970-01-01 00:00:01.775313945,2026-04-04 14:45:45
1593,1775315270,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17996132753759009:1775315270...,1970-01-01 00:00:01.775315270,2026-04-04 15:07:50
1594,1775347188,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18401097919195000:1775347188...,1970-01-01 00:00:01.775347188,2026-04-04 23:59:48

IT'S SECONDS!!!!! I should have started with that. Also shout out to pandas userguide, I went right along that list to figure out. Okay now to get this the table to match the one for tiktok

In [ ]:
IG2A["Date"]=IG2A["datetime"].dt.date
IG2A.head()

,timestamp,media,label_values,fbid,date,datetime,Date
0,1774902960,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18107755963665605:1774902960...,1970-01-01 00:00:01.774902960,2026-03-30 20:36:00,2026-03-30
1,1774905887,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18310119415256128:1774905887...,1970-01-01 00:00:01.774905887,2026-03-30 21:24:47,2026-03-30
2,1774908114,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18578712475019167:1774908114...,1970-01-01 00:00:01.774908114,2026-03-30 22:01:54,2026-03-30
3,1774911917,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18062489216380208:1774911917...,1970-01-01 00:00:01.774911917,2026-03-30 23:05:17,2026-03-30
4,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17952887547103349:1774912335...,1970-01-01 00:00:01.774912335,2026-03-30 23:12:15,2026-03-30

In [ ]:
IG2A["Day"]=IG2A["datetime"].dt.day_name()
IG2A.head()

,timestamp,media,label_values,fbid,date,datetime,Date,Day
0,1774902960,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18107755963665605:1774902960...,1970-01-01 00:00:01.774902960,2026-03-30 20:36:00,2026-03-30,Monday
1,1774905887,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18310119415256128:1774905887...,1970-01-01 00:00:01.774905887,2026-03-30 21:24:47,2026-03-30,Monday
2,1774908114,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18578712475019167:1774908114...,1970-01-01 00:00:01.774908114,2026-03-30 22:01:54,2026-03-30,Monday
3,1774911917,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18062489216380208:1774911917...,1970-01-01 00:00:01.774911917,2026-03-30 23:05:17,2026-03-30,Monday
4,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17952887547103349:1774912335...,1970-01-01 00:00:01.774912335,2026-03-30 23:12:15,2026-03-30,Monday

In [ ]:
IG2A["Watch Time"] = IG2A["datetime"].diff().abs()
IG2A.head()

,timestamp,media,label_values,fbid,date,datetime,Date,Day,Watch Time
0,1774902960,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18107755963665605:1774902960...,1970-01-01 00:00:01.774902960,2026-03-30 20:36:00,2026-03-30,Monday,NaT
1,1774905887,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18310119415256128:1774905887...,1970-01-01 00:00:01.774905887,2026-03-30 21:24:47,2026-03-30,Monday,0 days 00:48:47
2,1774908114,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18578712475019167:1774908114...,1970-01-01 00:00:01.774908114,2026-03-30 22:01:54,2026-03-30,Monday,0 days 00:37:07
3,1774911917,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18062489216380208:1774911917...,1970-01-01 00:00:01.774911917,2026-03-30 23:05:17,2026-03-30,Monday,0 days 01:03:23
4,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17952887547103349:1774912335...,1970-01-01 00:00:01.774912335,2026-03-30 23:12:15,2026-03-30,Monday,0 days 00:06:58

In [ ]:
IG2A["Time"]=IG2A["datetime"].dt.time
IG2A.head()

,timestamp,media,label_values,fbid,date,datetime,Date,Day,Watch Time,Time
0,1774902960,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18107755963665605:1774902960...,1970-01-01 00:00:01.774902960,2026-03-30 20:36:00,2026-03-30,Monday,NaT,20:36:00
1,1774905887,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18310119415256128:1774905887...,1970-01-01 00:00:01.774905887,2026-03-30 21:24:47,2026-03-30,Monday,0 days 00:48:47,21:24:47
2,1774908114,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18578712475019167:1774908114...,1970-01-01 00:00:01.774908114,2026-03-30 22:01:54,2026-03-30,Monday,0 days 00:37:07,22:01:54
3,1774911917,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18062489216380208:1774911917...,1970-01-01 00:00:01.774911917,2026-03-30 23:05:17,2026-03-30,Monday,0 days 01:03:23,23:05:17
4,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17952887547103349:1774912335...,1970-01-01 00:00:01.774912335,2026-03-30 23:12:15,2026-03-30,Monday,0 days 00:06:58,23:12:15

In [ ]:
Makeitwork = IG2A.assign(Platform="Instagram", Person="A")[['Platform', 'Person'] + IG2A.columns.tolist()]
Makeitwork.head()

,Platform,Person,timestamp,media,label_values,fbid,date,datetime,Date,Day,Watch Time,Time
0,Instagram,A,1774902960,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18107755963665605:1774902960...,1970-01-01 00:00:01.774902960,2026-03-30 20:36:00,2026-03-30,Monday,NaT,20:36:00
1,Instagram,A,1774905887,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18310119415256128:1774905887...,1970-01-01 00:00:01.774905887,2026-03-30 21:24:47,2026-03-30,Monday,0 days 00:48:47,21:24:47
2,Instagram,A,1774908114,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18578712475019167:1774908114...,1970-01-01 00:00:01.774908114,2026-03-30 22:01:54,2026-03-30,Monday,0 days 00:37:07,22:01:54
3,Instagram,A,1774911917,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18062489216380208:1774911917...,1970-01-01 00:00:01.774911917,2026-03-30 23:05:17,2026-03-30,Monday,0 days 01:03:23,23:05:17
4,Instagram,A,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17952887547103349:1774912335...,1970-01-01 00:00:01.774912335,2026-03-30 23:12:15,2026-03-30,Monday,0 days 00:06:58,23:12:15

In [ ]:
IDidit = Makeitwork[["Platform", "Person", "Date", "Day", "Time", "Watch Time"]]
IDidit.head()

    Platform Person        Date     Day      Time      Watch Time
0  Instagram      A  2026-03-30  Monday  20:36:00             NaT
1  Instagram      A  2026-03-30  Monday  21:24:47 0 days 00:48:47
2  Instagram      A  2026-03-30  Monday  22:01:54 0 days 00:37:07
3  Instagram      A  2026-03-30  Monday  23:05:17 0 days 01:03:23
4  Instagram      A  2026-03-30  Monday  23:12:15 0 days 00:06:58

Julia Notes: 
3 data frames to get to final for Instagram 
I think 3 for Tiktok 
2 for Instagram

### For Replication: 
*This is a work in progress*
Instagram Table 1: 
Naming convention: 
First, 
Final needs to be IG1(thenletter)

Steps 
1. with open("FILENAME.json") as j:
    IGrecommendedtopics = json.load(j) 
2. topics = [item['string_map_data']['Name']['value'] for item in IGrecommendedtopics['topics_your_topics']]
3. 

Tiktok Table 1: 
Naming convention: 
Final needs to be TT1(thenletter)

Instagram Table 2: 

Tiktok Table 2:

In [ ]:
## df_tiktok["Login History"].iloc[6]

In [ ]:
TTlogin= pd.DataFrame(df_tiktok["Login History"].iloc[6])

In [ ]:
TTlogin.head()

,Date,IP,DeviceModel,DeviceSystem,NetworkType,Carrier
0,2024-12-26 00:01:54,75.38.153.117,"iPhone17,2",iOS 18.1.1,Wi-Fi,
1,2024-12-26 00:11:53,75.38.153.117,"iPhone17,2",iOS 18.1.1,Wi-Fi,
2,2024-12-26 00:16:17,75.38.153.117,"iPhone17,2",iOS 18.1.1,Wi-Fi,
3,2024-12-26 00:22:33,75.38.153.117,"iPhone17,2",iOS 18.1.1,Wi-Fi,
4,2024-12-26 00:23:45,75.38.153.117,"iPhone17,2",iOS 18.1.1,Wi-Fi,

In [ ]:
type(TTlogin["Date"])

pandas.core.series.Series

It's never datetime. That's my number one take away from IG and TT downloadable data.

Notes from talking to Dr. Silva in class: OKAY! Changing things up. 
Concat- Post view time and video view time, cron. order. 
Take Log in time 

For tiktok 
df_logins 
df_watches in 

df.watches.iloc [new.index -1 ]

### Below is IG Post View Time

In [ ]:
with open("Julia Beta posts_viewed.json") as j:
    IGpostviewed = json.load(j)
IGpostviewed

[{'timestamp': 1774909773,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWgxvTrlPfF/',
    'href': 'https://www.instagram.com/p/DWgxvTrlPfF/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': 'https://likeshop.me/tmz_tv'},
       {'label': 'Name', 'value': 'TMZ'},
       {'label': 'Username', 'value': 'tmz_tv'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18591305350002568:1774909773::DYIImpressionsData'},
 {'timestamp': 1774909773,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWhcKrhifPf/',
    'href': 'https://www.instagram.com/p/DWhcKrhifPf/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': 'http://kalesaladfamous.com'},
       {'label': 'Name', 'value': 'Memes'},
       {'label': 'Username', 'value': 'kalesalad'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18187645741372271:1774909773::DYIImpressionsData'},
 {'timestamp': 1774910577,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWhJ_8aFDP1/',
    'href': 'https://www.instagram.com/p/DWhJ_8aFDP1/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': 'http://sunday-scaries.com'},
       {'label': 'Name', 'value': 'Sunday Scaries'},
       {'label': 'Username', 'value': 'sunday.scaries'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18085570352350779:1774910577::DYIImpressionsData'},
 {'timestamp': 1774912335,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWg3KiEjMsr/',
    'href': 'https://www.instagram.com/p/DWg3KiEjMsr/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/chinaminutes'},
       {'label': 'Name', 'value': 'CHINA MINUTES'},
       {'label': 'Username', 'value': 'chinaminutes'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17932913811218141:1774912335::DYIImpressionsData'},
 {'timestamp': 1774912335,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWhqh0EidVW/',
    'href': 'https://www.instagram.com/p/DWhqh0EidVW/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': 'http://kalesaladfamous.com'},
       {'label': 'Name', 'value': 'Memes'},
       {'label': 'Username', 'value': 'kalesalad'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18098571358814201:1774912335::DYIImpressionsData'},
 {'timestamp': 1774912335,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWhq7gwmksoWcoepadB3l-sE-U_b7-xCDrkS2o0/',
    'href': 'https://www.instagram.com/p/DWhq7gwmksoWcoepadB3l-sE-U_b7-xCDrkS2o0/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'Sarah Zettler'},
       {'label': 'Username', 'value': 'sarahdamage'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18063133322690868:1774912335::DYIImpressionsData'},
 {'timestamp': 1774912756,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWPdiJMEjO7/',
    'href': 'https://www.instagram.com/p/DWPdiJMEjO7/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linkin.bio/kvellercom'},
       {'label': 'Name', 'value': 'Kveller'},
       {'label': 'Username', 'value': 'kvellercom'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18002349890895837:1774912756::DYIImpressionsData'},
 {'timestamp': 1774913127,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWhQPh1kQHS/',
    'href': 'https://www.instagram.com/p/DWhQPh1kQHS/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'Instagramâ\x80\x99s @Creators'},
       {'label': 'Username', 'value': 'creators'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18387634531083067:1774913127::DYIImpressionsData'},
 {'timestamp': 1774918035,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWh0aAjjIvXFHVXvNX44_l78DGcjCgiNBYfBqw0/',
    'href': 'https://www.instagram.com/p/DWh0aAjjIvXFHVXvNX44_l78DGcjCgiNBYfBqw0/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'Karen'},
       {'label': 'Username', 'value': 'ktaloipa'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17933564049051651:1774918035::DYIImpressionsData'},
 {'timestamp': 1774919931,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWhGsTgjZeA/',
    'href': 'https://www.instagram.com/p/DWhGsTgjZeA/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://amber-skye-alcock.myshopify.com/pages/limited-edition-prints'},
       {'label': 'Name', 'value': 'Amber Skye Alcock'},
       {'label': 'Username', 'value': 'amberskyealcock'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18095821484108843:1774919931::DYIImpressionsData'},
 {'timestamp': 1774919957,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWfZj6hDngf/',
    'href': 'https://www.instagram.com/p/DWfZj6hDngf/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://docs.google.com/forms/d/e/1FAIpQLSd-xawtGWjcOvBcMALC5ki72jWw_N6tpHdIH-IAzafhIez5Nw/viewform'},
       {'label': 'Name', 'value': 'Abortion Rights Philly'},
       {'label': 'Username', 'value': 'abortionrightsphilly'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18101022445943392:1774919957::DYIImpressionsData'},
 {'timestamp': 1774919980,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWh7DbDE85o/',
    'href': 'https://www.instagram.com/p/DWh7DbDE85o/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'Kayla Sciuto'},
       {'label': 'Username', 'value': 'kaykaysciuto'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18090731122905228:1774919980::DYIImpressionsData'},
 {'timestamp': 1774919989,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DVyluDAEc0_/',
    'href': 'https://www.instagram.com/p/DVyluDAEc0_/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://lnk.bio/iamsadieolson'},
       {'label': 'Name', 'value': 'sadie the witch'},
       {'label': 'Username', 'value': 'iamsadieolson'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18082383227202994:1774919989::DYIImpressionsData'},
 {'timestamp': 1774920013,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWMHCLHEfC_/',
    'href': 'https://www.instagram.com/p/DWMHCLHEfC_/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/katiegrossbard'},
       {'label': 'Name', 'value': 'Katie Grossbard'},
       {'label': 'Username', 'value': 'katiegrossbard'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17912636814167115:1774920013::DYIImpressionsData'},
 {'timestamp': 1774921611,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWhOV2EllBw/',
    'href': 'https://www.instagram.com/p/DWhOV2EllBw/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'Femislay'},
       {'label': 'Username', 'value': 'femislay'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18083926721348747:1774921611::DYIImpressionsData'},
 {'timestamp': 1774921750,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWcltqikh8H/',
    'href': 'https://www.instagram.com/p/DWcltqikh8H/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktree.com/TrainerRem'},
       {'label': 'Name', 'value': 'â\x9a¡ï¸\x8fTrainerRemâ\x9a¡ï¸\x8f'},
       {'label': 'Username', 'value': 'trainerrem'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18111746917706258:1774921750::DYIImpressionsData'},
 {'timestamp': 1774925270,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWiA9L8D3u3/',
    'href': 'https://www.instagram.com/p/DWiA9L8D3u3/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://www.tiktok.com/@mha.mahamek'},
       {'label': 'Name',
        'value': 'à¸«à¸¡à¸²à¸\x88à¸\xadà¸¡à¹\x80à¸§à¸\x97à¸¢à¹\x8c à¸¡à¸«à¸²à¹\x80à¸¡à¸\x86'},
       {'label': 'Username', 'value': 'mha.mahamek'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18031919363633179:1774925270::DYIImpressionsData'},
 {'timestamp': 1774925284,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWWtEMmDK7-/',
    'href': 'https://www.instagram.com/p/DWWtEMmDK7-/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': 'https://www.primecaviar.pl'},
       {'label': 'Name', 'value': 'PRIMECAVIAR by Paulina Rogal | Ceramika'},
       {'label': 'Username', 'value': 'primecaviar'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18130269937483779:1774925284::DYIImpressionsData'},
 {'timestamp': 1774956525,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWiLB8WjRH5/',
    'href': 'https://www.instagram.com/p/DWiLB8WjRH5/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/wiwibloggs'},
       {'label': 'Name', 'value': 'wiwibloggs'},
       {'label': 'Username', 'value': 'wiwibloggs'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17951813406108349:1774956525::DYIImpressionsData'},
 {'timestamp': 1774956570,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWg0CiqjBbY/',
    'href': 'https://www.instagram.com/p/DWg0CiqjBbY/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/amirabdallahcomedy'},
       {'label': 'Name', 'value': 'Amir'},
       {'label': 'Username', 'value': 'theamirabdallah'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18354074464226457:1774956570::DYIImpressionsData'},
 {'timestamp': 1774956611,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWUBoXHFRjh/',
    'href': 'https://www.instagram.com/p/DWUBoXHFRjh/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://beacons.ai/neel.ghost'},
       {'label': 'Name', 'value': 'Neel Ghosh'},
       {'label': 'Username', 'value': 'neel.ghost'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18098603266800809:1774956611::DYIImpressionsData'},
 {'timestamp': 1774956684,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWW1Qf0DBiq/',
    'href': 'https://www.instagram.com/p/DWW1Qf0DBiq/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://ko-fi.com/butchmonologues?ref=onboarding_email_founderwelcome'},
       {'label': 'Name', 'value': 'The butch monologues'},
       {'label': 'Username', 'value': 'butchmonologues'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18084183242610525:1774956684::DYIImpressionsData'},
 {'timestamp': 1774956684,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWg_QLRFs59/',
    'href': 'https://www.instagram.com/p/DWg_QLRFs59/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://www.netflixisajokefest.com/'},
       {'label': 'Name', 'value': 'Netflix Is A Joke'},
       {'label': 'Username', 'value': 'netflixisajoke'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18578441140003829:1774956684::DYIImpressionsData'},
 {'timestamp': 1774962439,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWgxF24ltuO/',
    'href': 'https://www.instagram.com/p/DWgxF24ltuO/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/halanscott'},
       {'label': 'Name', 'value': 'H. Alan Scott'},
       {'label': 'Username', 'value': 'halanscott'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:17890237362333528:1774962439::DYIImpressionsData'},
 {'timestamp': 1774962439,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWh2wu9gSy7/',
    'href': 'https://www.instagram.com/p/DWh2wu9gSy7/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/bindiirwin'},
       {'label': 'Name', 'value': 'Bindi Irwin'},
       {'label': 'Username', 'value': 'bindisueirwin'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18354750697236303:1774962439::DYIImpressionsData'},
 {'timestamp': 1774979362,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWjPPvVgi0s/',
    'href': 'https://www.instagram.com/p/DWjPPvVgi0s/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'http://www.eurovision.com/app'},
       {'label': 'Name', 'value': 'Eurovision Song Contest'},
       {'label': 'Username', 'value': 'eurovision'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18101363341766265:1774979362::DYIImpressionsData'},
 {'timestamp': 1774979362,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWjWgcAjsBc/',
    'href': 'https://www.instagram.com/p/DWjWgcAjsBc/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'http://www.rescuecity.nyc/adopt'},
       {'label': 'Name', 'value': 'Rescue City ð\x9f\x90¶'},
       {'label': 'Username', 'value': 'rescuecity'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18084718859606793:1774979362::DYIImpressionsData'},
 {'timestamp': 1774980128,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWjpLqKlN-1/',
    'href': 'https://www.instagram.com/p/DWjpLqKlN-1/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://internetshaquille.com/affiliates'},
       {'label': 'Name', 'value': 'Internet Shaquille'},
       {'label': 'Username', 'value': 'internetshaquille'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18425354542190252:1774980128::DYIImpressionsData'},
 {'timestamp': 1774989731,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWjnGMekg8Y/',
    'href': 'https://www.instagram.com/p/DWjnGMekg8Y/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linkin.bio/thehardtimesnews'},
       {'label': 'Name', 'value': 'The Hard Times'},
       {'label': 'Username', 'value': 'thehardtimesnews'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18096735704056013:1774989731::DYIImpressionsData'},
 {'timestamp': 1774989750,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWh0YkZjzz1/',
    'href': 'https://www.instagram.com/p/DWh0YkZjzz1/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://www.petco.com/shop/en/petcostore?cm_mmc=OSM%257CMETA%257COMNI%257CCC%257CNA%257CNA%257CwYfqebfBJqW7oKmFiQstP3%257C0%257C0%257C0%257C0'},
       {'label': 'Name', 'value': 'Petco'},
       {'label': 'Username', 'value': 'petco'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18194468299351875:1774989750::DYIImpressionsData'},
 {'timestamp': 1774989762,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWg69JBDKp8/',
    'href': 'https://www.instagram.com/p/DWg69JBDKp8/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'RageBait Mediað\x9f\x94\x87'},
       {'label': 'Username', 'value': 'ragebaitnews'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18114483655663976:1774989762::DYIImpressionsData'},
 {'timestamp': 1774989794,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWjnNBClNxA/',
    'href': 'https://www.instagram.com/p/DWjnNBClNxA/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linkin.bio/reductress/'},
       {'label': 'Name', 'value': 'Reductress'},
       {'label': 'Username', 'value': 'reductress'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18126183256575488:1774989794::DYIImpressionsData'},
 {'timestamp': 1774989825,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWeyoW-mG4P/',
    'href': 'https://www.instagram.com/p/DWeyoW-mG4P/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': 'http://deluludesigns.com'},
       {'label': 'Name', 'value': 'Delulu Designsâ\x84¢'},
       {'label': 'Username', 'value': 'shopdeluludesigns'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18452812792106162:1774989825::DYIImpressionsData'},
 {'timestamp': 1774989828,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWaeSO8jqzj/',
    'href': 'https://www.instagram.com/p/DWaeSO8jqzj/'},
   {'dict': [{'dict': [{'label': 'URL', 'value': ''},
       {'label': 'Name', 'value': 'Men Beings Happy'},
       {'label': 'Username', 'value': 'mensbeingshappy'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18088360675971029:1774989828::DYIImpressionsData'},
 {'timestamp': 1774989837,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWhFuVaiZvr/',
    'href': 'https://www.instagram.com/p/DWhFuVaiZvr/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linkin.bio/reductress/'},
       {'label': 'Name', 'value': 'Reductress'},
       {'label': 'Username', 'value': 'reductress'}],
      'title': ''}],
    'title': 'Owner'}],
  'fbid': '17841400448200474:18572526724029665:1774989837::DYIImpressionsData'},
 {'timestamp': 1774989901,
  'media': [],
  'label_values': [{'label': 'Ad library public URL'},
   {'label': 'URL',
    'value': 'https://www.instagram.com/p/DWg3evxD4Sn/',
    'href': 'https://www.instagram.com/p/DWg3evxD4Sn/'},
   {'dict': [{'dict': [{'label': 'URL',
        'value': 'https://linktr.ee/MadisonMallards'},

In [ ]:
PostViewHistory = pd.DataFrame(IGpostviewed)
PostViewHistory.head()

,timestamp,media,label_values,fbid
0,1774909773,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18591305350002568:1774909773...
1,1774909773,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18187645741372271:1774909773...
2,1774910577,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18085570352350779:1774910577...
3,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17932913811218141:1774912335...
4,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18098571358814201:1774912335...

...Well it's good that the layout is the same as the video one

In [ ]:
PostViewHistory['datetime'] = pd.to_datetime(PostViewHistory['timestamp'], unit='s')
PostViewHistory.head()

,timestamp,media,label_values,fbid,datetime
0,1774909773,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18591305350002568:1774909773...,2026-03-30 22:29:33
1,1774909773,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18187645741372271:1774909773...,2026-03-30 22:29:33
2,1774910577,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18085570352350779:1774910577...,2026-03-30 22:42:57
3,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17932913811218141:1774912335...,2026-03-30 23:12:15
4,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18098571358814201:1774912335...,2026-03-30 23:12:15

In [ ]:
PostViewHistory["Time"]=PostViewHistory["datetime"].dt.time
PostViewHistory.head()

,timestamp,media,label_values,fbid,datetime,Time
0,1774909773,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18591305350002568:1774909773...,2026-03-30 22:29:33,22:29:33
1,1774909773,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18187645741372271:1774909773...,2026-03-30 22:29:33,22:29:33
2,1774910577,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18085570352350779:1774910577...,2026-03-30 22:42:57,22:42:57
3,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17932913811218141:1774912335...,2026-03-30 23:12:15,23:12:15
4,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18098571358814201:1774912335...,2026-03-30 23:12:15,23:12:15

In [ ]:
PostViewHistorywithLabels = PostViewHistory.assign(Posting="Post", Person="A")[["Posting", "Person"] + PostViewHistory.columns.tolist()]
PostViewHistorywithLabels.head()

,Posting,Person,timestamp,media,label_values,fbid,datetime,Time
0,Post,A,1774909773,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18591305350002568:1774909773...,2026-03-30 22:29:33,22:29:33
1,Post,A,1774909773,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18187645741372271:1774909773...,2026-03-30 22:29:33,22:29:33
2,Post,A,1774910577,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18085570352350779:1774910577...,2026-03-30 22:42:57,22:42:57
3,Post,A,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17932913811218141:1774912335...,2026-03-30 23:12:15,23:12:15
4,Post,A,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18098571358814201:1774912335...,2026-03-30 23:12:15,23:12:15

In [ ]:
ReadyToConCatIGPost = PostViewHistorywithLabels[["Posting", "Person", "datetime", "Time"]]
ReadyToConCatIGPost.head()

  Posting Person            datetime      Time
0    Post      A 2026-03-30 22:29:33  22:29:33
1    Post      A 2026-03-30 22:29:33  22:29:33
2    Post      A 2026-03-30 22:42:57  22:42:57
3    Post      A 2026-03-30 23:12:15  23:12:15
4    Post      A 2026-03-30 23:12:15  23:12:15

### Great now to get the table to mirror that for video

In [ ]:
AlmostReadyToConCatIGVideo= Makeitwork.assign(Posting="Video")[["Posting"] + Makeitwork.columns.tolist()]
AlmostReadyToConCatIGVideo.head()

,Posting,Platform,Person,timestamp,media,label_values,fbid,date,datetime,Date,Day,Watch Time,Time
0,Video,Instagram,A,1774902960,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18107755963665605:1774902960...,1970-01-01 00:00:01.774902960,2026-03-30 20:36:00,2026-03-30,Monday,NaT,20:36:00
1,Video,Instagram,A,1774905887,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18310119415256128:1774905887...,1970-01-01 00:00:01.774905887,2026-03-30 21:24:47,2026-03-30,Monday,0 days 00:48:47,21:24:47
2,Video,Instagram,A,1774908114,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18578712475019167:1774908114...,1970-01-01 00:00:01.774908114,2026-03-30 22:01:54,2026-03-30,Monday,0 days 00:37:07,22:01:54
3,Video,Instagram,A,1774911917,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:18062489216380208:1774911917...,1970-01-01 00:00:01.774911917,2026-03-30 23:05:17,2026-03-30,Monday,0 days 01:03:23,23:05:17
4,Video,Instagram,A,1774912335,[],"[{'label': 'Ad library public URL'}, {'label':...",17841400448200474:17952887547103349:1774912335...,1970-01-01 00:00:01.774912335,2026-03-30 23:12:15,2026-03-30,Monday,0 days 00:06:58,23:12:15

In [ ]:
ReadyToConCatIGVideo = AlmostReadyToConCatIGVideo[["Posting","Person", "datetime", "Time"]]
ReadyToConCatIGVideo.head()

  Posting Person            datetime      Time
0   Video      A 2026-03-30 20:36:00  20:36:00
1   Video      A 2026-03-30 21:24:47  21:24:47
2   Video      A 2026-03-30 22:01:54  22:01:54
3   Video      A 2026-03-30 23:05:17  23:05:17
4   Video      A 2026-03-30 23:12:15  23:12:15

Took out the IG tag and putting in Video. Maybe I need IG but tbh I'm more worried about Concatting lol
Okay my goal is to concat AND put the date time in chronological order.

In [ ]:
FULLIGWatchHistory = pd.concat([ReadyToConCatIGPost, ReadyToConCatIGVideo]).sort_values("datetime")
FULLIGWatchHistory.head()

   Posting Person            datetime      Time
5    Video      A 2026-03-24 01:19:10  01:19:10
6    Video      A 2026-03-24 20:45:00  20:45:00
38    Post      A 2026-03-25 01:10:44  01:10:44
39    Post      A 2026-03-25 01:41:36  01:41:36
40    Post      A 2026-03-25 03:03:20  03:03:20

In [ ]:
FULLIGWatchHistory.tail()

     Posting Person            datetime      Time
1250    Post      A 2026-04-06 19:54:03  19:54:03
1246    Post      A 2026-04-06 19:54:03  19:54:03
1247    Post      A 2026-04-06 19:54:03  19:54:03
1249    Post      A 2026-04-06 19:54:03  19:54:03
1248    Post      A 2026-04-06 19:54:03  19:54:03

DID IT WORK? I THINK SO. I got very confused with the concat index = true portion but I left it out and it looks.. fine? The colum on the left hand side is totally throwing me but OKAY

Now I need to make the log in time a date time. JOY! 
Okay thing to note.... I did not originally download Log in information so this one is going to be wonky. The other ones will NOT be wonky.

In [ ]:
with open("Julia Beta_login_activity.json") as j:
    IGLoginInfo = json.load(j)
## IGLoginInfo

{'account_history_login_history': [{'title': '2026-03-20T20:29:25+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************yOy',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1702:3020:20f0:55f1:6175:faa8:1343',
     'timestamp': 0},
    'Port': {'href': '', 'value': '41130', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1774038565},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36',
     'timestamp': 0}}},
  {'title': '2026-03-20T20:28:42+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************iO8',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1702:3020:20f0:8927:6f5d:ecfc:d650',
     'timestamp': 0},
    'Port': {'href': '', 'value': '48350', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1774038522},
    'User Agent': {'href': '',
     'value': 'Instagram 421.1.6.39.52 (iPhone17,2; iOS 26_3_1; en_US; en; scale=3.00; 1320x2868; 910922286) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2026-03-20T20:28:16+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************iO8',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1702:3020:20f0:8927:6f5d:ecfc:d650',
     'timestamp': 0},
    'Port': {'href': '', 'value': '58415', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1774038496},
    'User Agent': {'href': '',
     'value': 'Instagram 421.1.6.39.52 (iPhone17,2; iOS 26_3_1; en_US; en; scale=3.00; 1320x2868; 910922286) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2026-03-19T22:56:09+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************yOy',
     'timestamp': 0},
    'IP Address': {'href': '', 'value': '131.123.227.18', 'timestamp': 0},
    'Port': {'href': '', 'value': '60707', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1773960969},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36',
     'timestamp': 0}}},
  {'title': '2026-03-19T22:52:23+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************iO8',
     'timestamp': 0},
    'IP Address': {'href': '', 'value': '131.123.227.105', 'timestamp': 0},
    'Port': {'href': '', 'value': '55315', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1773960743},
    'User Agent': {'href': '',
     'value': 'Instagram 420.0.0.39.76 (iPhone17,2; iOS 26_3_1; en_US; en; scale=3.00; 1320x2868; 904620799) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2025-02-08T23:24:13+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************iO8',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1702:3020:20f0:8d06:5c6f:315d:38ba',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1739057053},
    'User Agent': {'href': '',
     'value': 'Barcelona 366.1.0.20.104 (iPhone17,2; iOS 18_3; en_US; en; scale=3.00; 1320x2868; 693537538) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2024-03-21T23:27:18+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************BnG',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1009:b024:ce06:d522:5513:1bae:43a4',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1711063638},
    'User Agent': {'href': '',
     'value': 'Instagram 323.0.3.23.54 (iPhone13,3; iOS 16_3_1; en_US; en; scale=3.00; 1170x2532; 577210397) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2024-03-21T23:27:16+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************BnG',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1009:b024:ce06:d522:5513:1bae:43a4',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1711063636},
    'User Agent': {'href': '',
     'value': 'Instagram 323.0.3.23.54 (iPhone13,3; iOS 16_3_1; en_US; en; scale=3.00; 1170x2532; 577210397) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2023-11-23T03:12:16+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************BnG',
     'timestamp': 0},
    'IP Address': {'href': '', 'value': '108.209.120.50', 'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1700709136},
    'User Agent': {'href': '',
     'value': 'Instagram 309.1.1.28.108 (iPhone13,3; iOS 16_3_1; en_US; en; scale=3.00; 1170x2532; 537288535) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2023-07-06T10:10:45+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************BnG',
     'timestamp': 0},
    'IP Address': {'href': '', 'value': '108.249.12.124', 'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1688638245},
    'User Agent': {'href': '',
     'value': 'Barcelona 289.0.0.22.50 (iPhone13,3; iOS 16_3_1; en_US; en; scale=3.00; 1170x2532; 489338310) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2023-06-09T21:23:56+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************BnG',
     'timestamp': 0},
    'IP Address': {'href': '', 'value': '107.216.51.182', 'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1686345836},
    'User Agent': {'href': '',
     'value': 'Instagram 285.0.0.13.63 (iPhone13,3; iOS 16_3_1; en_US; en; scale=3.00; 1170x2532; 478871389) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2022-11-22T21:42:13+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************BnG',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1009:b068:d30c:8426:b122:ecec:85ce',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1669153333},
    'User Agent': {'href': '',
     'value': 'Instagram 261.0.0.18.106 (iPhone13,3; iOS 16_1_1; en_US; en-US; scale=3.00; 1170x2532; 418330231) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2022-01-04T14:45:57+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************9gj',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:d4ef:42cf:b746:8b8b',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1641307557},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_8_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1',
     'timestamp': 0}}},
  {'title': '2022-01-04T14:43:29+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************gBj',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:d4ef:42cf:b746:8b8b',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1641307409},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_8_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148',
     'timestamp': 0}}},
  {'title': '2022-01-04T14:40:25+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************Ai_',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:d4ef:42cf:b746:8b8b',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1641307225},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_8_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1',
     'timestamp': 0}}},
  {'title': '2021-12-06T05:03:28+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************BnG',
     'timestamp': 0},
    'IP Address': {'href': '', 'value': '100.33.85.6', 'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1638767008},
    'User Agent': {'href': '',
     'value': 'Instagram 214.0.0.36.111 (iPhone13,3; iOS 14_8_1; en_US; en-US; scale=3.00; 1170x2532; 332901305) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2021-10-12T16:47:51+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************MuX',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:89d1:1501:f471:df89',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1634057271},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36',
     'timestamp': 0}}},
  {'title': '2021-07-26T22:32:24+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************BnG',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:99c0:22:4e75:2573',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1627338744},
    'User Agent': {'href': '',
     'value': 'Instagram 197.0.0.20.119 (iPhone13,3; iOS 14_6; en_US; en-US; scale=3.00; 1170x2532; 305020938) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2021-07-01T17:37:49+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************MuX',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:3591:bfab:1f6:2b06',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1625161069},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36',
     'timestamp': 0}}},
  {'title': '2021-01-05T15:44:41+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************BnG',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:60fd:114d:6d98:4c30',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1609861481},
    'User Agent': {'href': '',
     'value': 'Instagram 169.0.0.21.133 (iPhone13,3; iOS 14_2_1; en_US; en-US; scale=3.00; 1170x2532; 261791898) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2020-12-31T02:54:22+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************iB1',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:688a:e89e:66ec:7cc2',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1609383262},
    'User Agent': {'href': '',
     'value': 'Instagram 167.0.0.18.114 (iPad8,11; iOS 14_0; en_US; en-US; scale=2.00; 1334x750; 257196069) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2020-12-29T19:45:32+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************BnG',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1009:b0da:3538:c1bb:15e0:6fa8:d17c',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1609271132},
    'User Agent': {'href': '',
     'value': 'Instagram 169.0.0.21.133 (iPhone13,3; iOS 14_2_1; en_US; en-US; scale=3.00; 1170x2532; 261791898) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2020-12-29T19:44:26+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************Ai_',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1009:b0da:3538:c1bb:15e0:6fa8:d17c',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1609271066},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Mobile/15E148 Safari/604.1',
     'timestamp': 0}}},
  {'title': '2020-11-07T18:17:44+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************MuX',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:1cf1:2377:58f2:40fd',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1604773064},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36',
     'timestamp': 0}}},
  {'title': '2020-10-08T19:52:08+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************MuX',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:c176:e313:3c6c:73da',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1602186728},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36',
     'timestamp': 0}}},
  {'title': '2020-09-25T18:49:11+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************tqh',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:4403:39e9:e4bf:931c',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1601059751},
    'User Agent': {'href': '',
     'value': 'Instagram 160.1.0.31.120 (iPad8,11; iOS 14_0; en_US; en-US; scale=2.00; 1334x750; 246979827) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2020-09-25T17:44:13+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************HMh',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:d827:5d39:7315:8564',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1601055853},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/125.2.332137730 Mobile/15E148 Safari/604.1',
     'timestamp': 0}}},
  {'title': '2020-09-14T22:46:14+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************2Bo',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:7020:dcf:bd5c:e0ae',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1600123574},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
     'timestamp': 0}}},
  {'title': '2020-09-02T18:55:34+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************BnG',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:38f9:e55f:c53:2b68',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1599072934},
    'User Agent': {'href': '',
     'value': 'Instagram 157.0.0.23.119 (iPhone10,2; iOS 13_6_1; en_US; en-US; scale=2.61; 1080x1920; 241452311) AppleWebKit/420+',
     'timestamp': 0}}},
  {'title': '2020-09-02T18:51:24+00:00',
   'media_map_data': {},
   'string_map_data': {'Cookie Name': {'href': '',
     'value': '*************************2Bo',
     'timestamp': 0},
    'IP Address': {'href': '',
     'value': '2600:1700:59d1:ccf0:3581:d251:3dce:a43b',
     'timestamp': 0},
    'Port': {'href': '', 'value': '0', 'timestamp': 0},
    'Language Code': {'href': '', 'value': 'en', 'timestamp': 0},
    'Time': {'href': '', 'value': '', 'timestamp': 1599072684},
    'User Agent': {'href': '',
     'value': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
     'timestamp': 0}}},

In [ ]:
IGLoginInfo.keys()
IGLoginInfo['account_history_login_history'][0]['string_map_data']["Time"]['timestamp']

1774038565

In [ ]:
times = [x['string_map_data']["Time"]['timestamp'] for x in IGLoginInfo['account_history_login_history']]

IGLogInTime= pd.DataFrame({'login_information': pd.to_datetime(times, unit='s')})
IGLogInTime['login_information']

0    2026-03-20 20:29:25
1    2026-03-20 20:28:42
2    2026-03-20 20:28:16
3    2026-03-19 22:56:09
4    2026-03-19 22:52:23
             ...
63   2017-02-23 19:24:04
64   2017-02-23 19:23:40
65   2017-02-23 01:34:18
66   2017-02-10 05:50:36
67   2016-12-04 20:30:05
Name: login_information, Length: 68, dtype: datetime64[ns]

In [ ]:
IGLogInTime['login_information'].iloc[0]

Timestamp('2026-03-20 20:29:25')

In [ ]:
FULLIGWatchHistory["datetime"] in ['2017-02-23 19:24:04']

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
FULLIGWatchHistory[FULLIGWatchHistory["datetime"] in list(IGLogInTime["login_information"])]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

SO I'm stuck........... so I'm going to make a Heat Graph draft to keep the progress moving forward... I just want to figure out how to do it. 

So alot of these heat maps are.... simple. https://stackoverflow.com/questions/71549352/plotly-express-heatmap-using-pandas-dataframe FUN

#### We did in fact NOT do it, Joe. 
But we're getting close.

Next steps: 
1. String-ify date time to use the x for x in to get the actual watch time. Finalize that table. 
2. Copy and Paste all the code that I actually need into a reference document so I can start on a clean slate with student data and have a template to work with to make the most of my time. 
3. A draft of a heat map, the can I am forever kicking down the road but NO LONGER.