In [1]:
import pandas as pd

In [6]:
data_dict = {'a': [1,2,3], 'b': [4,5,6]}
data_list = [{'a': 1, 'b': 4}, {'a': 2, 'b': 5}, {'a': 3, 'b': 6}]

dat = pd.DataFrame(data_dict)
dat

   a  b
0  1  4
1  2  5
2  3  6

In [7]:
dat2 = pd.DataFrame(data_list)
dat2

   a  b
0  1  4
1  2  5
2  3  6

In [9]:
dat.head(1)

   a  b
0  1  4

In [10]:
dat.tail(1)

   a  b
2  3  6

In [11]:
dat['a']

0    1
1    2
2    3
Name: a, dtype: int64

In [12]:
dat.loc[0]

a    1
b    4
Name: 0, dtype: int64

In [14]:
dat.iloc[0]

a    1
b    4
Name: 0, dtype: int64

In [15]:
dat.index

RangeIndex(start=0, stop=3, step=1)

In [16]:
len(dat.index)

3

In [17]:
len(dat.columns)

2

In [19]:
dat[['a','b']]

   a  b
0  1  4
1  2  5
2  3  6

In [20]:
dat[ dat['a'] > 2]

   a  b
2  3  6

In [22]:
dat[ dat['a'] > 2]['a']

2    3
Name: a, dtype: int64

In [23]:
dat.to_csv("KeaheyPandasChallenge.csv")


### What does the "write/render/evaluate" loop provide for creators of interactive data visualizations?
The write/render/evaluate loop allows for refinement of a desigN, By writing code, then rendering it, we can see what assess what could be improved upon and what is already working. When it comes to interactive data one of the potential refinement areass is if our data viz is easily understood by anyone who is not familar with our data set. 

### Why are dynamic, interactive data visualizations useful when communicating data?
Interactive data visulatizations are useful when communicating data as it can break down large amounts of data. Looking at data sets over years or with multiple variables can be extremely overwhemling but the interactivity allows users to dive deeper and get more details on a data set. This aligns with the, “'Visual Information-Seeking Mantra”: overview first, zoom and filter, then details-on-demand." Static images do not allow users to filter and get details on demand. 

### Do you agree with Murray's claim that open-source tools that avoid proprietary software are best for publishing data visualization? In a few sentences, explain why you do or do not agree.
I do agree with that. Avoiding proprietary software allows for increased accessibility. 
I can see this through working at Kent State, recently in our office we purchased a video editing software designed for beginners called PlayPlay. The process to get this software tool over a year, the lenghty process went multiple levels of approval starting with my boss to the director to an SVP, then through legal who had red lines to the contract, then the other company had to respond to redlines, then after that process concluded the financial team could weigh in on if they felt it was a good use of budget, then there was a logisitic of payment and paperwork for our Tax free status. This is the standard process, but open-source avoids that process entirely making it more cost-effective, accessible, and faster.